//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_EMPRESA3_Entities : DbContext
    {
        public BD_EMPRESA3_Entities()
            : base("name=BD_EMPRESA3_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_acao_banner> tb_acao_banner { get; set; }
        public virtual DbSet<tb_analise_spd_conta> tb_analise_spd_conta { get; set; }
        public virtual DbSet<tb_api_copa> tb_api_copa { get; set; }
        public virtual DbSet<tb_aux_developer> tb_aux_developer { get; set; }
        public virtual DbSet<tb_aux_developer_operadora> tb_aux_developer_operadora { get; set; }
        public virtual DbSet<tb_avaliacao> tb_avaliacao { get; set; }
        public virtual DbSet<tb_banco> tb_banco { get; set; }
        public virtual DbSet<tb_banco_conta_digital> tb_banco_conta_digital { get; set; }
        public virtual DbSet<tb_banner> tb_banner { get; set; }
        public virtual DbSet<tb_black_list> tb_black_list { get; set; }
        public virtual DbSet<tb_black_list_usuario_forma_pagamento> tb_black_list_usuario_forma_pagamento { get; set; }
        public virtual DbSet<tb_bloqueio_cartao> tb_bloqueio_cartao { get; set; }
        public virtual DbSet<tb_boleto> tb_boleto { get; set; }
        public virtual DbSet<tb_campanha> tb_campanha { get; set; }
        public virtual DbSet<tb_canal> tb_canal { get; set; }
        public virtual DbSet<tb_cartao_tarifa_sptrans> tb_cartao_tarifa_sptrans { get; set; }
        public virtual DbSet<tb_chave_pix> tb_chave_pix { get; set; }
        public virtual DbSet<tb_cidade> tb_cidade { get; set; }
        public virtual DbSet<tb_conta> tb_conta { get; set; }
        public virtual DbSet<tb_controle> tb_controle { get; set; }
        public virtual DbSet<tb_crm_motivo_relacionamento> tb_crm_motivo_relacionamento { get; set; }
        public virtual DbSet<tb_crm_protocolo_atendimento> tb_crm_protocolo_atendimento { get; set; }
        public virtual DbSet<tb_crm_relacionamento> tb_crm_relacionamento { get; set; }
        public virtual DbSet<tb_crm_relacionamento_arquivos> tb_crm_relacionamento_arquivos { get; set; }
        public virtual DbSet<tb_crm_relacionamento_usr_atribuido> tb_crm_relacionamento_usr_atribuido { get; set; }
        public virtual DbSet<tb_crm_situacao_relacionamento> tb_crm_situacao_relacionamento { get; set; }
        public virtual DbSet<tb_crm_situacao_relacionamento_usr_atribuido> tb_crm_situacao_relacionamento_usr_atribuido { get; set; }
        public virtual DbSet<tb_crm_tipo_relacionamento> tb_crm_tipo_relacionamento { get; set; }
        public virtual DbSet<tb_cupom> tb_cupom { get; set; }
        public virtual DbSet<tb_cupom_categoria_loja> tb_cupom_categoria_loja { get; set; }
        public virtual DbSet<tb_cupom_loja> tb_cupom_loja { get; set; }
        public virtual DbSet<tb_cupom_oferta> tb_cupom_oferta { get; set; }
        public virtual DbSet<tb_cupom_usuario> tb_cupom_usuario { get; set; }
        public virtual DbSet<tb_diagnostico_contas_dock> tb_diagnostico_contas_dock { get; set; }
        public virtual DbSet<tb_dicionario_erro> tb_dicionario_erro { get; set; }
        public virtual DbSet<tb_duvida> tb_duvida { get; set; }
        public virtual DbSet<tb_duvida_assunto> tb_duvida_assunto { get; set; }
        public virtual DbSet<tb_duvida_assunto_revenda> tb_duvida_assunto_revenda { get; set; }
        public virtual DbSet<tb_duvida_revenda> tb_duvida_revenda { get; set; }
        public virtual DbSet<tb_envio_email> tb_envio_email { get; set; }
        public virtual DbSet<tb_erro_abertura_conta> tb_erro_abertura_conta { get; set; }
        public virtual DbSet<tb_erro_sistema> tb_erro_sistema { get; set; }
        public virtual DbSet<tb_estado_civil> tb_estado_civil { get; set; }
        public virtual DbSet<tb_estorno_pedido> tb_estorno_pedido { get; set; }
        public virtual DbSet<tb_estorno_pedido_item> tb_estorno_pedido_item { get; set; }
        public virtual DbSet<tb_estudante_complemento> tb_estudante_complemento { get; set; }
        public virtual DbSet<tb_estudante_grau> tb_estudante_grau { get; set; }
        public virtual DbSet<tb_estudante_serie> tb_estudante_serie { get; set; }
        public virtual DbSet<tb_estudante_turno> tb_estudante_turno { get; set; }
        public virtual DbSet<tb_etapa_status_via> tb_etapa_status_via { get; set; }
        public virtual DbSet<tb_etapa_via> tb_etapa_via { get; set; }
        public virtual DbSet<tb_etapa_via_rejeicao> tb_etapa_via_rejeicao { get; set; }
        public virtual DbSet<tb_faq> tb_faq { get; set; }
        public virtual DbSet<tb_fastcash_phill> tb_fastcash_phill { get; set; }
        public virtual DbSet<tb_fila_analise_revalidacao> tb_fila_analise_revalidacao { get; set; }
        public virtual DbSet<tb_fila_envio_email> tb_fila_envio_email { get; set; }
        public virtual DbSet<tb_fila_notificacao> tb_fila_notificacao { get; set; }
        public virtual DbSet<tb_fluxo_etapa_via> tb_fluxo_etapa_via { get; set; }
        public virtual DbSet<tb_forma_pagamento> tb_forma_pagamento { get; set; }
        public virtual DbSet<tb_formulario_pergunta> tb_formulario_pergunta { get; set; }
        public virtual DbSet<tb_formulario_resposta_usuario> tb_formulario_resposta_usuario { get; set; }
        public virtual DbSet<tb_gateway> tb_gateway { get; set; }
        public virtual DbSet<tb_gateway_fastcash> tb_gateway_fastcash { get; set; }
        public virtual DbSet<tb_ged_pedido> tb_ged_pedido { get; set; }
        public virtual DbSet<tb_ged_pedido_cartao> tb_ged_pedido_cartao { get; set; }
        public virtual DbSet<tb_ged_pedido_cash_in> tb_ged_pedido_cash_in { get; set; }
        public virtual DbSet<tb_ged_revalidacao> tb_ged_revalidacao { get; set; }
        public virtual DbSet<tb_ged_temporario> tb_ged_temporario { get; set; }
        public virtual DbSet<tb_historico_pedido_pagamento_picpay> tb_historico_pedido_pagamento_picpay { get; set; }
        public virtual DbSet<tb_historico_requisicao_via> tb_historico_requisicao_via { get; set; }
        public virtual DbSet<tb_importacao_adyen> tb_importacao_adyen { get; set; }
        public virtual DbSet<tb_instrucao_boleto> tb_instrucao_boleto { get; set; }
        public virtual DbSet<tb_integracao> tb_integracao { get; set; }
        public virtual DbSet<tb_integracao_historico> tb_integracao_historico { get; set; }
        public virtual DbSet<tb_integracao_parametro_notificacao> tb_integracao_parametro_notificacao { get; set; }
        public virtual DbSet<tb_EMPRESA3lometros> tb_EMPRESA3lometros { get; set; }
        public virtual DbSet<tb_EMPRESA3lometros_config> tb_EMPRESA3lometros_config { get; set; }
        public virtual DbSet<tb_EMPRESA3lometros_expirados> tb_EMPRESA3lometros_expirados { get; set; }
        public virtual DbSet<tb_EMPRESA3lometros_integracoes_diarias> tb_EMPRESA3lometros_integracoes_diarias { get; set; }
        public virtual DbSet<tb_EMPRESA3lometros_resgate> tb_EMPRESA3lometros_resgate { get; set; }
        public virtual DbSet<tb_linha_itinerario> tb_linha_itinerario { get; set; }
        public virtual DbSet<tb_linha_paradas> tb_linha_paradas { get; set; }
        public virtual DbSet<tb_log_alt_telefone> tb_log_alt_telefone { get; set; }
        public virtual DbSet<tb_log_black_list> tb_log_black_list { get; set; }
        public virtual DbSet<tb_log_black_list_usuario_forma_pagamento> tb_log_black_list_usuario_forma_pagamento { get; set; }
        public virtual DbSet<tb_log_conciliacao_fastcash> tb_log_conciliacao_fastcash { get; set; }
        public virtual DbSet<tb_log_doacao> tb_log_doacao { get; set; }
        public virtual DbSet<tb_log_email> tb_log_email { get; set; }
        public virtual DbSet<tb_log_erro_abertura_conta> tb_log_erro_abertura_conta { get; set; }
        public virtual DbSet<tb_log_localizacao_usuario> tb_log_localizacao_usuario { get; set; }
        public virtual DbSet<tb_log_notificacao_gateway> tb_log_notificacao_gateway { get; set; }
        public virtual DbSet<tb_log_pedido> tb_log_pedido { get; set; }
        public virtual DbSet<tb_log_pedido_estocagem> tb_log_pedido_estocagem { get; set; }
        public virtual DbSet<tb_log_pedido_item> tb_log_pedido_item { get; set; }
        public virtual DbSet<tb_log_pedido_item_cancelamento_rv> tb_log_pedido_item_cancelamento_rv { get; set; }
        public virtual DbSet<tb_log_registro> tb_log_registro { get; set; }
        public virtual DbSet<tb_log_sbe> tb_log_sbe { get; set; }
        public virtual DbSet<tb_log_sms> tb_log_sms { get; set; }
        public virtual DbSet<tb_log_terminal> tb_log_terminal { get; set; }
        public virtual DbSet<tb_log_usuario_alteracao> tb_log_usuario_alteracao { get; set; }
        public virtual DbSet<tb_log_usuario_cartao> tb_log_usuario_cartao { get; set; }
        public virtual DbSet<tb_log_usuario_programa_fidelidade> tb_log_usuario_programa_fidelidade { get; set; }
        public virtual DbSet<tb_log_usuario_revenda> tb_log_usuario_revenda { get; set; }
        public virtual DbSet<tb_log_usuario_revenda_comissao> tb_log_usuario_revenda_comissao { get; set; }
        public virtual DbSet<tb_log_usuario_revenda_limite> tb_log_usuario_revenda_limite { get; set; }
        public virtual DbSet<tb_log_usuario_revenda_suspenso> tb_log_usuario_revenda_suspenso { get; set; }
        public virtual DbSet<tb_menu_adm> tb_menu_adm { get; set; }
        public virtual DbSet<tb_motivo_baixa> tb_motivo_baixa { get; set; }
        public virtual DbSet<tb_nacionalidade> tb_nacionalidade { get; set; }
        public virtual DbSet<tb_natureza_juridica> tb_natureza_juridica { get; set; }
        public virtual DbSet<tb_notificacao> tb_notificacao { get; set; }
        public virtual DbSet<tb_ofertas> tb_ofertas { get; set; }
        public virtual DbSet<tb_ofertas_categoria> tb_ofertas_categoria { get; set; }
        public virtual DbSet<tb_ofertas_loja> tb_ofertas_loja { get; set; }
        public virtual DbSet<tb_operadora> tb_operadora { get; set; }
        public virtual DbSet<tb_operadora_acerto> tb_operadora_acerto { get; set; }
        public virtual DbSet<tb_operadora_banco_conta> tb_operadora_banco_conta { get; set; }
        public virtual DbSet<tb_operadora_cidade> tb_operadora_cidade { get; set; }
        public virtual DbSet<tb_operadora_empresa> tb_operadora_empresa { get; set; }
        public virtual DbSet<tb_operadora_empresa_tipo_cartao> tb_operadora_empresa_tipo_cartao { get; set; }
        public virtual DbSet<tb_operadora_forma_pagamento_gateway> tb_operadora_forma_pagamento_gateway { get; set; }
        public virtual DbSet<tb_operadora_linha> tb_operadora_linha { get; set; }
        public virtual DbSet<tb_operadora_mapa_params> tb_operadora_mapa_params { get; set; }
        public virtual DbSet<tb_operadora_mensagem> tb_operadora_mensagem { get; set; }
        public virtual DbSet<tb_operadora_parceiro_logistico> tb_operadora_parceiro_logistico { get; set; }
        public virtual DbSet<tb_operadora_revenda_secundaria> tb_operadora_revenda_secundaria { get; set; }
        public virtual DbSet<tb_operadora_tipo_canal> tb_operadora_tipo_canal { get; set; }
        public virtual DbSet<tb_operadora_versao_api> tb_operadora_versao_api { get; set; }
        public virtual DbSet<tb_orgao_emissor> tb_orgao_emissor { get; set; }
        public virtual DbSet<tb_pagamento_pedido_parcelado> tb_pagamento_pedido_parcelado { get; set; }
        public virtual DbSet<tb_pagina> tb_pagina { get; set; }
        public virtual DbSet<tb_pagina_controle> tb_pagina_controle { get; set; }
        public virtual DbSet<tb_pagina_cupom> tb_pagina_cupom { get; set; }
        public virtual DbSet<tb_paradas> tb_paradas { get; set; }
        public virtual DbSet<tb_parameto_itau> tb_parameto_itau { get; set; }
        public virtual DbSet<tb_parametro> tb_parametro { get; set; }
        public virtual DbSet<tb_parametro_anti_fraude> tb_parametro_anti_fraude { get; set; }
        public virtual DbSet<tb_parametro_cashback> tb_parametro_cashback { get; set; }
        public virtual DbSet<tb_parametro_cashdeal> tb_parametro_cashdeal { get; set; }
        public virtual DbSet<tb_parametro_comissao> tb_parametro_comissao { get; set; }
        public virtual DbSet<tb_parametro_email> tb_parametro_email { get; set; }
        public virtual DbSet<tb_parametro_parcelamento> tb_parametro_parcelamento { get; set; }
        public virtual DbSet<tb_parametro_pix_wso> tb_parametro_pix_wso { get; set; }
        public virtual DbSet<tb_parametro_revenda_comissao> tb_parametro_revenda_comissao { get; set; }
        public virtual DbSet<tb_parametro_rv> tb_parametro_rv { get; set; }
        public virtual DbSet<tb_parametro_tentativa_most> tb_parametro_tentativa_most { get; set; }
        public virtual DbSet<tb_parametro_terceiro> tb_parametro_terceiro { get; set; }
        public virtual DbSet<tb_parceiro_logistico> tb_parceiro_logistico { get; set; }
        public virtual DbSet<tb_pedido> tb_pedido { get; set; }
        public virtual DbSet<tb_pedido_atm> tb_pedido_atm { get; set; }
        public virtual DbSet<tb_pedido_cash_in> tb_pedido_cash_in { get; set; }
        public virtual DbSet<tb_pedido_entrega> tb_pedido_entrega { get; set; }
        public virtual DbSet<tb_pedido_item> tb_pedido_item { get; set; }
        public virtual DbSet<tb_pedido_item_cartao> tb_pedido_item_cartao { get; set; }
        public virtual DbSet<tb_pedido_pagamento_picpay> tb_pedido_pagamento_picpay { get; set; }
        public virtual DbSet<tb_pedido_pagamento_pix> tb_pedido_pagamento_pix { get; set; }
        public virtual DbSet<tb_pedido_revenda> tb_pedido_revenda { get; set; }
        public virtual DbSet<tb_pedido_rv> tb_pedido_rv { get; set; }
        public virtual DbSet<tb_perfil> tb_perfil { get; set; }
        public virtual DbSet<tb_perfil_sub_menu_adm> tb_perfil_sub_menu_adm { get; set; }
        public virtual DbSet<tb_posto> tb_posto { get; set; }
        public virtual DbSet<tb_posto_operadora> tb_posto_operadora { get; set; }
        public virtual DbSet<tb_programa_fidelidade> tb_programa_fidelidade { get; set; }
        public virtual DbSet<tb_programa_fidelidade_resgate> tb_programa_fidelidade_resgate { get; set; }
        public virtual DbSet<tb_quadro_horario> tb_quadro_horario { get; set; }
        public virtual DbSet<tb_recarga_automatica> tb_recarga_automatica { get; set; }
        public virtual DbSet<tb_recarga_programada> tb_recarga_programada { get; set; }
        public virtual DbSet<tb_rel_liq_cobranca> tb_rel_liq_cobranca { get; set; }
        public virtual DbSet<tb_remessa_cobranca> tb_remessa_cobranca { get; set; }
        public virtual DbSet<tb_requisicao_qrcode> tb_requisicao_qrcode { get; set; }
        public virtual DbSet<tb_requisicao_via> tb_requisicao_via { get; set; }
        public virtual DbSet<tb_servico> tb_servico { get; set; }
        public virtual DbSet<tb_status_conta> tb_status_conta { get; set; }
        public virtual DbSet<tb_status_conta_dock> tb_status_conta_dock { get; set; }
        public virtual DbSet<tb_status_entrega> tb_status_entrega { get; set; }
        public virtual DbSet<tb_status_pedido> tb_status_pedido { get; set; }
        public virtual DbSet<tb_status_pedido_item> tb_status_pedido_item { get; set; }
        public virtual DbSet<tb_status_pedido_pagamento_picpay> tb_status_pedido_pagamento_picpay { get; set; }
        public virtual DbSet<tb_status_pedido_pagamento_pix> tb_status_pedido_pagamento_pix { get; set; }
        public virtual DbSet<tb_status_requisicao_via> tb_status_requisicao_via { get; set; }
        public virtual DbSet<tb_sub_menu_adm> tb_sub_menu_adm { get; set; }
        public virtual DbSet<tb_tarefa_entrega> tb_tarefa_entrega { get; set; }
        public virtual DbSet<tb_tarifa> tb_tarifa { get; set; }
        public virtual DbSet<tb_taxa_adm> tb_taxa_adm { get; set; }
        public virtual DbSet<tb_taxa_operadora_tipo_cartao> tb_taxa_operadora_tipo_cartao { get; set; }
        public virtual DbSet<tb_tentativa_most> tb_tentativa_most { get; set; }
        public virtual DbSet<tb_terminal> tb_terminal { get; set; }
        public virtual DbSet<tb_termo_de_uso> tb_termo_de_uso { get; set; }
        public virtual DbSet<tb_termo_operadora> tb_termo_operadora { get; set; }
        public virtual DbSet<tb_tipo_canal> tb_tipo_canal { get; set; }
        public virtual DbSet<tb_tipo_cartao> tb_tipo_cartao { get; set; }
        public virtual DbSet<tb_tipo_cartao_estoque> tb_tipo_cartao_estoque { get; set; }
        public virtual DbSet<tb_tipo_cartao_forma_pagamento> tb_tipo_cartao_forma_pagamento { get; set; }
        public virtual DbSet<tb_tipo_cartao_tecnologia> tb_tipo_cartao_tecnologia { get; set; }
        public virtual DbSet<tb_tipo_cartao_valor> tb_tipo_cartao_valor { get; set; }
        public virtual DbSet<tb_tipo_controle> tb_tipo_controle { get; set; }
        public virtual DbSet<tb_tipo_documento> tb_tipo_documento { get; set; }
        public virtual DbSet<tb_tipo_email> tb_tipo_email { get; set; }
        public virtual DbSet<tb_tipo_endereco> tb_tipo_endereco { get; set; }
        public virtual DbSet<tb_tipo_notificacao> tb_tipo_notificacao { get; set; }
        public virtual DbSet<tb_tipo_ocupacao> tb_tipo_ocupacao { get; set; }
        public virtual DbSet<tb_tipo_pedido_item> tb_tipo_pedido_item { get; set; }
        public virtual DbSet<tb_tipo_pedido_item_fluxo_status> tb_tipo_pedido_item_fluxo_status { get; set; }
        public virtual DbSet<tb_tipo_telefone> tb_tipo_telefone { get; set; }
        public virtual DbSet<tb_tipo_transacao> tb_tipo_transacao { get; set; }
        public virtual DbSet<tb_transacao_conta_digital> tb_transacao_conta_digital { get; set; }
        public virtual DbSet<tb_transacao_programa_fidelidade> tb_transacao_programa_fidelidade { get; set; }
        public virtual DbSet<tb_uf> tb_uf { get; set; }
        public virtual DbSet<tb_usuario> tb_usuario { get; set; }
        public virtual DbSet<tb_usuario_adm> tb_usuario_adm { get; set; }
        public virtual DbSet<tb_usuario_adm_operadora_empresa> tb_usuario_adm_operadora_empresa { get; set; }
        public virtual DbSet<tb_usuario_banco_conta> tb_usuario_banco_conta { get; set; }
        public virtual DbSet<tb_usuario_banco_conta_chave> tb_usuario_banco_conta_chave { get; set; }
        public virtual DbSet<tb_usuario_cartao> tb_usuario_cartao { get; set; }
        public virtual DbSet<tb_usuario_cartao_credito> tb_usuario_cartao_credito { get; set; }
        public virtual DbSet<tb_usuario_cartao_credito_endereco_cobranca> tb_usuario_cartao_credito_endereco_cobranca { get; set; }
        public virtual DbSet<tb_usuario_cartao_credito_gateway_token> tb_usuario_cartao_credito_gateway_token { get; set; }
        public virtual DbSet<tb_usuario_cartao_favorito_linha> tb_usuario_cartao_favorito_linha { get; set; }
        public virtual DbSet<tb_usuario_conta_corrente> tb_usuario_conta_corrente { get; set; }
        public virtual DbSet<tb_usuario_cupom> tb_usuario_cupom { get; set; }
        public virtual DbSet<tb_usuario_dependente> tb_usuario_dependente { get; set; }
        public virtual DbSet<tb_usuario_dependente_documento_banco> tb_usuario_dependente_documento_banco { get; set; }
        public virtual DbSet<tb_usuario_documento_banco> tb_usuario_documento_banco { get; set; }
        public virtual DbSet<tb_usuario_endereco> tb_usuario_endereco { get; set; }
        public virtual DbSet<tb_usuario_equipamento> tb_usuario_equipamento { get; set; }
        public virtual DbSet<tb_usuario_favorito_linha> tb_usuario_favorito_linha { get; set; }
        public virtual DbSet<tb_usuario_favorito_paradas> tb_usuario_favorito_paradas { get; set; }
        public virtual DbSet<tb_usuario_revenda_comissao> tb_usuario_revenda_comissao { get; set; }
        public virtual DbSet<tb_usuario_revenda_operadora> tb_usuario_revenda_operadora { get; set; }
        public virtual DbSet<tb_usuario_revenda_pre_estocagem> tb_usuario_revenda_pre_estocagem { get; set; }
        public virtual DbSet<tb_usuario_saldo> tb_usuario_saldo { get; set; }
        public virtual DbSet<tb_usuario_solicitacao_exclusao> tb_usuario_solicitacao_exclusao { get; set; }
        public virtual DbSet<tb_usuario_termo_de_uso> tb_usuario_termo_de_uso { get; set; }
        public virtual DbSet<tb_valores_sptrans> tb_valores_sptrans { get; set; }
        public virtual DbSet<tb_modelo_email> tb_modelo_email { get; set; }
        public virtual DbSet<vw_bi_relacionamento_usuario> vw_bi_relacionamento_usuario { get; set; }
        public virtual DbSet<vw_bi_tb_crm_motivo_relacionamento> vw_bi_tb_crm_motivo_relacionamento { get; set; }
        public virtual DbSet<vw_bi_tb_crm_tipo_relacionamento> vw_bi_tb_crm_tipo_relacionamento { get; set; }
        public virtual DbSet<vw_bi_tb_operadora> vw_bi_tb_operadora { get; set; }
        public virtual DbSet<vw_bi_tb_perfil> vw_bi_tb_perfil { get; set; }
        public virtual DbSet<vw_bi_tb_tipo_cartao> vw_bi_tb_tipo_cartao { get; set; }
        public virtual DbSet<vw_bi_tb_usuario> vw_bi_tb_usuario { get; set; }
        public virtual DbSet<vw_bi_tb_usuario_adm> vw_bi_tb_usuario_adm { get; set; }
        public virtual DbSet<vw_bi_tb_usuario_pedido> vw_bi_tb_usuario_pedido { get; set; }
        public virtual DbSet<vw_bi_usuario_cadastro_cartao> vw_bi_usuario_cadastro_cartao { get; set; }
        public virtual DbSet<vw_bi_usuario_pedidos> vw_bi_usuario_pedidos { get; set; }
        public virtual DbSet<vw_bi_vendas> vw_bi_vendas { get; set; }
        public virtual DbSet<vw_Cupom_Disponivel_Usuario> vw_Cupom_Disponivel_Usuario { get; set; }
        public virtual DbSet<vw_EMPRESA3lometros_agrupados> vw_EMPRESA3lometros_agrupados { get; set; }
        public virtual DbSet<vw_Pedidos_AntiFraude> vw_Pedidos_AntiFraude { get; set; }
        public virtual DbSet<vw_Pedidos_AntiFraude_Recarga_Celular> vw_Pedidos_AntiFraude_Recarga_Celular { get; set; }
        public virtual DbSet<vw_Pedidos_AntiFraude_Servicos_Digitais> vw_Pedidos_AntiFraude_Servicos_Digitais { get; set; }
        public virtual DbSet<vw_pedidos_pagar_operadora> vw_pedidos_pagar_operadora { get; set; }
        public virtual DbSet<vw_qnt_usuarios_operadoras> vw_qnt_usuarios_operadoras { get; set; }
        public virtual DbSet<vw_SaldoBloqueado> vw_SaldoBloqueado { get; set; }
        public virtual DbSet<vw_ServicosOperadoras> vw_ServicosOperadoras { get; set; }
        public virtual DbSet<vw_UsuarioCartaoOperadora> vw_UsuarioCartaoOperadora { get; set; }
        public virtual DbSet<vw_VendasRevenda> vw_VendasRevenda { get; set; }
        public virtual DbSet<vwListDashBoard> vwListDashBoard { get; set; }
    
        public virtual int sp_altera_status_relacionamento_atribuido(Nullable<decimal> cd_relacionamento)
        {
            var cd_relacionamentoParameter = cd_relacionamento.HasValue ?
                new ObjectParameter("cd_relacionamento", cd_relacionamento) :
                new ObjectParameter("cd_relacionamento", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_altera_status_relacionamento_atribuido", cd_relacionamentoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_atualiza_black_list(string nu_cartao, Nullable<int> cd_tipo_cartao, string nu_cpf_usuario, string ds_email_usuario)
        {
            var nu_cartaoParameter = nu_cartao != null ?
                new ObjectParameter("nu_cartao", nu_cartao) :
                new ObjectParameter("nu_cartao", typeof(string));
    
            var cd_tipo_cartaoParameter = cd_tipo_cartao.HasValue ?
                new ObjectParameter("cd_tipo_cartao", cd_tipo_cartao) :
                new ObjectParameter("cd_tipo_cartao", typeof(int));
    
            var nu_cpf_usuarioParameter = nu_cpf_usuario != null ?
                new ObjectParameter("nu_cpf_usuario", nu_cpf_usuario) :
                new ObjectParameter("nu_cpf_usuario", typeof(string));
    
            var ds_email_usuarioParameter = ds_email_usuario != null ?
                new ObjectParameter("ds_email_usuario", ds_email_usuario) :
                new ObjectParameter("ds_email_usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_atualiza_black_list", nu_cartaoParameter, cd_tipo_cartaoParameter, nu_cpf_usuarioParameter, ds_email_usuarioParameter);
        }
    
        public virtual int sp_atualiza_status_pedido(string ds_pedido_operadora, Nullable<int> cd_pedido_item, Nullable<short> cd_status_pedido_item, Nullable<System.DateTime> ds_dt_datahora_pedido_operadora)
        {
            var ds_pedido_operadoraParameter = ds_pedido_operadora != null ?
                new ObjectParameter("ds_pedido_operadora", ds_pedido_operadora) :
                new ObjectParameter("ds_pedido_operadora", typeof(string));
    
            var cd_pedido_itemParameter = cd_pedido_item.HasValue ?
                new ObjectParameter("cd_pedido_item", cd_pedido_item) :
                new ObjectParameter("cd_pedido_item", typeof(int));
    
            var cd_status_pedido_itemParameter = cd_status_pedido_item.HasValue ?
                new ObjectParameter("cd_status_pedido_item", cd_status_pedido_item) :
                new ObjectParameter("cd_status_pedido_item", typeof(short));
    
            var ds_dt_datahora_pedido_operadoraParameter = ds_dt_datahora_pedido_operadora.HasValue ?
                new ObjectParameter("ds_dt_datahora_pedido_operadora", ds_dt_datahora_pedido_operadora) :
                new ObjectParameter("ds_dt_datahora_pedido_operadora", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_atualiza_status_pedido", ds_pedido_operadoraParameter, cd_pedido_itemParameter, cd_status_pedido_itemParameter, ds_dt_datahora_pedido_operadoraParameter);
        }
    
        public virtual int sp_atualiza_status_pedido_item(Nullable<int> cd_pedido_item, Nullable<short> cd_status_pedido_item)
        {
            var cd_pedido_itemParameter = cd_pedido_item.HasValue ?
                new ObjectParameter("cd_pedido_item", cd_pedido_item) :
                new ObjectParameter("cd_pedido_item", typeof(int));
    
            var cd_status_pedido_itemParameter = cd_status_pedido_item.HasValue ?
                new ObjectParameter("cd_status_pedido_item", cd_status_pedido_item) :
                new ObjectParameter("cd_status_pedido_item", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_atualiza_status_pedido_item", cd_pedido_itemParameter, cd_status_pedido_itemParameter);
        }
    
        public virtual int sp_CompareDb(string sourceDB, string targetDb)
        {
            var sourceDBParameter = sourceDB != null ?
                new ObjectParameter("SourceDB", sourceDB) :
                new ObjectParameter("SourceDB", typeof(string));
    
            var targetDbParameter = targetDb != null ?
                new ObjectParameter("TargetDb", targetDb) :
                new ObjectParameter("TargetDb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CompareDb", sourceDBParameter, targetDbParameter);
        }
    
        public virtual ObjectResult<sp_consulta_cancelar_pedidos_Result> sp_consulta_cancelar_pedidos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_cancelar_pedidos_Result>("sp_consulta_cancelar_pedidos");
        }
    
        public virtual ObjectResult<sp_consulta_cancelar_pedidos_itens_Result> sp_consulta_cancelar_pedidos_itens(Nullable<long> cd_pedido)
        {
            var cd_pedidoParameter = cd_pedido.HasValue ?
                new ObjectParameter("cd_pedido", cd_pedido) :
                new ObjectParameter("cd_pedido", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_cancelar_pedidos_itens_Result>("sp_consulta_cancelar_pedidos_itens", cd_pedidoParameter);
        }
    
        public virtual ObjectResult<sp_consulta_cupom_Result> sp_consulta_cupom(Nullable<long> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_cupom_Result>("sp_consulta_cupom", usuarioParameter);
        }
    
        public virtual ObjectResult<sp_consulta_historico_pedido_Result> sp_consulta_historico_pedido(Nullable<long> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_historico_pedido_Result>("sp_consulta_historico_pedido", usuarioParameter);
        }
    
        public virtual ObjectResult<sp_consulta_historico_pedido_status_Result> sp_consulta_historico_pedido_status(Nullable<long> usuario, Nullable<int> statuspedido)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(long));
    
            var statuspedidoParameter = statuspedido.HasValue ?
                new ObjectParameter("statuspedido", statuspedido) :
                new ObjectParameter("statuspedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_historico_pedido_status_Result>("sp_consulta_historico_pedido_status", usuarioParameter, statuspedidoParameter);
        }
    
        public virtual ObjectResult<sp_consulta_historico_revenda_pedido_status_Result> sp_consulta_historico_revenda_pedido_status(Nullable<long> usuario, Nullable<int> statuspedido)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(long));
    
            var statuspedidoParameter = statuspedido.HasValue ?
                new ObjectParameter("statuspedido", statuspedido) :
                new ObjectParameter("statuspedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_historico_revenda_pedido_status_Result>("sp_consulta_historico_revenda_pedido_status", usuarioParameter, statuspedidoParameter);
        }
    
        public virtual ObjectResult<sp_consulta_pedido_aguardando_recarga_Result> sp_consulta_pedido_aguardando_recarga()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_pedido_aguardando_recarga_Result>("sp_consulta_pedido_aguardando_recarga");
        }
    
        public virtual ObjectResult<sp_consulta_pedido_FastCash_arquivo_Result> sp_consulta_pedido_FastCash_arquivo(Nullable<long> cd_pedido, Nullable<int> tempo)
        {
            var cd_pedidoParameter = cd_pedido.HasValue ?
                new ObjectParameter("cd_pedido", cd_pedido) :
                new ObjectParameter("cd_pedido", typeof(long));
    
            var tempoParameter = tempo.HasValue ?
                new ObjectParameter("Tempo", tempo) :
                new ObjectParameter("Tempo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_pedido_FastCash_arquivo_Result>("sp_consulta_pedido_FastCash_arquivo", cd_pedidoParameter, tempoParameter);
        }
    
        public virtual ObjectResult<sp_consulta_pedido_historico_Result> sp_consulta_pedido_historico(Nullable<long> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_pedido_historico_Result>("sp_consulta_pedido_historico", usuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_consulta_pedido_seis_meses_fidelidade(Nullable<long> cd_usuario)
        {
            var cd_usuarioParameter = cd_usuario.HasValue ?
                new ObjectParameter("cd_usuario", cd_usuario) :
                new ObjectParameter("cd_usuario", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_consulta_pedido_seis_meses_fidelidade", cd_usuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_consulta_pedido_seis_meses_fidelidade_identificado(Nullable<long> cd_usuario)
        {
            var cd_usuarioParameter = cd_usuario.HasValue ?
                new ObjectParameter("cd_usuario", cd_usuario) :
                new ObjectParameter("cd_usuario", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_consulta_pedido_seis_meses_fidelidade_identificado", cd_usuarioParameter);
        }
    
        public virtual ObjectResult<sp_consulta_revalidacao_Result> sp_consulta_revalidacao()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_revalidacao_Result>("sp_consulta_revalidacao");
        }
    
        public virtual ObjectResult<sp_consulta_status_pedido_Result> sp_consulta_status_pedido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_status_pedido_Result>("sp_consulta_status_pedido");
        }
    
        public virtual ObjectResult<sp_consulta_status_pre_pedido_Result> sp_consulta_status_pre_pedido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_status_pre_pedido_Result>("sp_consulta_status_pre_pedido");
        }
    
        public virtual ObjectResult<sp_consulta_status_pre_pedido_pagamento_Result> sp_consulta_status_pre_pedido_pagamento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_status_pre_pedido_pagamento_Result>("sp_consulta_status_pre_pedido_pagamento");
        }
    
        public virtual ObjectResult<sp_consulta_terminal_ope_usuario_Result> sp_consulta_terminal_ope_usuario(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_terminal_ope_usuario_Result>("sp_consulta_terminal_ope_usuario", usuarioParameter);
        }
    
        public virtual ObjectResult<sp_consulta_terminal_operadora_Result> sp_consulta_terminal_operadora()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_terminal_operadora_Result>("sp_consulta_terminal_operadora");
        }
    
        public virtual ObjectResult<sp_consulta_ultimo_pedido_historico_Result> sp_consulta_ultimo_pedido_historico(Nullable<long> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_ultimo_pedido_historico_Result>("sp_consulta_ultimo_pedido_historico", usuarioParameter);
        }
    
        public virtual ObjectResult<sp_consulta_ultimo_pedido_historico_site_Result> sp_consulta_ultimo_pedido_historico_site(Nullable<long> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_ultimo_pedido_historico_site_Result>("sp_consulta_ultimo_pedido_historico_site", usuarioParameter);
        }
    
        public virtual ObjectResult<sp_consulta_usuario_cartao_Result> sp_consulta_usuario_cartao()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_usuario_cartao_Result>("sp_consulta_usuario_cartao");
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<sp_detalhes_cliente_Result> sp_detalhes_cliente(Nullable<int> cd_usuario)
        {
            var cd_usuarioParameter = cd_usuario.HasValue ?
                new ObjectParameter("cd_usuario", cd_usuario) :
                new ObjectParameter("cd_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_detalhes_cliente_Result>("sp_detalhes_cliente", cd_usuarioParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_exclui_programa_fidelidade(Nullable<int> cd_usuario)
        {
            var cd_usuarioParameter = cd_usuario.HasValue ?
                new ObjectParameter("cd_usuario", cd_usuario) :
                new ObjectParameter("cd_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_exclui_programa_fidelidade", cd_usuarioParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_lista_pedido_envio_email_Result> sp_lista_pedido_envio_email(Nullable<long> codigoPedido, Nullable<long> codigoUsuario)
        {
            var codigoPedidoParameter = codigoPedido.HasValue ?
                new ObjectParameter("codigoPedido", codigoPedido) :
                new ObjectParameter("codigoPedido", typeof(long));
    
            var codigoUsuarioParameter = codigoUsuario.HasValue ?
                new ObjectParameter("codigoUsuario", codigoUsuario) :
                new ObjectParameter("codigoUsuario", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lista_pedido_envio_email_Result>("sp_lista_pedido_envio_email", codigoPedidoParameter, codigoUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_lista_terminal_Result> sp_lista_terminal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lista_terminal_Result>("sp_lista_terminal");
        }
    
        public virtual ObjectResult<sp_lista_terminal_ope_usuario_Result> sp_lista_terminal_ope_usuario(Nullable<int> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lista_terminal_ope_usuario_Result>("sp_lista_terminal_ope_usuario", usuarioParameter);
        }
    
        public virtual ObjectResult<sp_notificacao_pedido_nao_pago_Result> sp_notificacao_pedido_nao_pago(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("dataInicial", dataInicial) :
                new ObjectParameter("dataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("dataFinal", dataFinal) :
                new ObjectParameter("dataFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_notificacao_pedido_nao_pago_Result>("sp_notificacao_pedido_nao_pago", dataInicialParameter, dataFinalParameter);
        }
    
        public virtual int sp_notificacao_usuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_notificacao_usuario");
        }
    
        public virtual int sp_push_valida_carga(Nullable<int> codigoUsuario, string mensagem, Nullable<int> tipoNotificacao)
        {
            var codigoUsuarioParameter = codigoUsuario.HasValue ?
                new ObjectParameter("CodigoUsuario", codigoUsuario) :
                new ObjectParameter("CodigoUsuario", typeof(int));
    
            var mensagemParameter = mensagem != null ?
                new ObjectParameter("Mensagem", mensagem) :
                new ObjectParameter("Mensagem", typeof(string));
    
            var tipoNotificacaoParameter = tipoNotificacao.HasValue ?
                new ObjectParameter("tipoNotificacao", tipoNotificacao) :
                new ObjectParameter("tipoNotificacao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_push_valida_carga", codigoUsuarioParameter, mensagemParameter, tipoNotificacaoParameter);
        }
    
        public virtual ObjectResult<sp_rel_acerto_operadora_Result> sp_rel_acerto_operadora(Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag, Nullable<int> cd_operadora, Nullable<int> cd_empresa)
        {
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            var cd_operadoraParameter = cd_operadora.HasValue ?
                new ObjectParameter("cd_operadora", cd_operadora) :
                new ObjectParameter("cd_operadora", typeof(int));
    
            var cd_empresaParameter = cd_empresa.HasValue ?
                new ObjectParameter("cd_empresa", cd_empresa) :
                new ObjectParameter("cd_empresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_acerto_operadora_Result>("sp_rel_acerto_operadora", dt_ini_pagParameter, dt_fim_pagParameter, cd_operadoraParameter, cd_empresaParameter);
        }
    
        public virtual ObjectResult<sp_rel_auditoria_EMPRESA3lometros_beneficios_Result> sp_rel_auditoria_EMPRESA3lometros_beneficios(Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag)
        {
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_auditoria_EMPRESA3lometros_beneficios_Result>("sp_rel_auditoria_EMPRESA3lometros_beneficios", dt_ini_pagParameter, dt_fim_pagParameter);
        }
    
        public virtual ObjectResult<sp_rel_bloqueio_Result> sp_rel_bloqueio(Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag, Nullable<int> cd_operadora, string cartao)
        {
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            var cd_operadoraParameter = cd_operadora.HasValue ?
                new ObjectParameter("cd_operadora", cd_operadora) :
                new ObjectParameter("cd_operadora", typeof(int));
    
            var cartaoParameter = cartao != null ?
                new ObjectParameter("cartao", cartao) :
                new ObjectParameter("cartao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_bloqueio_Result>("sp_rel_bloqueio", dt_ini_pagParameter, dt_fim_pagParameter, cd_operadoraParameter, cartaoParameter);
        }
    
        public virtual ObjectResult<sp_rel_cadastro_usuarios_Result> sp_rel_cadastro_usuarios(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("DataInicial", dataInicial) :
                new ObjectParameter("DataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("DataFinal", dataFinal) :
                new ObjectParameter("DataFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_cadastro_usuarios_Result>("sp_rel_cadastro_usuarios", dataInicialParameter, dataFinalParameter);
        }
    
        public virtual ObjectResult<sp_rel_cancelamentos_rv_Result> sp_rel_cancelamentos_rv(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("DataInicial", dataInicial) :
                new ObjectParameter("DataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("DataFinal", dataFinal) :
                new ObjectParameter("DataFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_cancelamentos_rv_Result>("sp_rel_cancelamentos_rv", dataInicialParameter, dataFinalParameter);
        }
    
        public virtual int sp_rel_cartaodrecredito_retorno(Nullable<int> cd_operadora, Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag, string idslistconcilia)
        {
            var cd_operadoraParameter = cd_operadora.HasValue ?
                new ObjectParameter("cd_operadora", cd_operadora) :
                new ObjectParameter("cd_operadora", typeof(int));
    
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            var idslistconciliaParameter = idslistconcilia != null ?
                new ObjectParameter("Idslistconcilia", idslistconcilia) :
                new ObjectParameter("Idslistconcilia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_rel_cartaodrecredito_retorno", cd_operadoraParameter, dt_ini_pagParameter, dt_fim_pagParameter, idslistconciliaParameter);
        }
    
        public virtual ObjectResult<sp_rel_carteira_digital_contas_Result> sp_rel_carteira_digital_contas(Nullable<int> status, Nullable<System.DateTime> dateInitial, Nullable<System.DateTime> dateEnd)
        {
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var dateInitialParameter = dateInitial.HasValue ?
                new ObjectParameter("DateInitial", dateInitial) :
                new ObjectParameter("DateInitial", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("DateEnd", dateEnd) :
                new ObjectParameter("DateEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_carteira_digital_contas_Result>("sp_rel_carteira_digital_contas", statusParameter, dateInitialParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<sp_rel_controle_pagamentos_usuario_Result> sp_rel_controle_pagamentos_usuario(Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag, Nullable<decimal> usr_id, Nullable<int> cd_operadora)
        {
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            var usr_idParameter = usr_id.HasValue ?
                new ObjectParameter("usr_id", usr_id) :
                new ObjectParameter("usr_id", typeof(decimal));
    
            var cd_operadoraParameter = cd_operadora.HasValue ?
                new ObjectParameter("cd_operadora", cd_operadora) :
                new ObjectParameter("cd_operadora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_controle_pagamentos_usuario_Result>("sp_rel_controle_pagamentos_usuario", dt_ini_pagParameter, dt_fim_pagParameter, usr_idParameter, cd_operadoraParameter);
        }
    
        public virtual ObjectResult<sp_rel_doacoes_Result> sp_rel_doacoes(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("DataInicial", dataInicial) :
                new ObjectParameter("DataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("DataFinal", dataFinal) :
                new ObjectParameter("DataFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_doacoes_Result>("sp_rel_doacoes", dataInicialParameter, dataFinalParameter);
        }
    
        public virtual ObjectResult<sp_rel_extratoEMPRESA3lometros_Result> sp_rel_extratoEMPRESA3lometros(Nullable<System.DateTime> dt_ini, Nullable<System.DateTime> dt_fim, Nullable<int> cdusuario)
        {
            var dt_iniParameter = dt_ini.HasValue ?
                new ObjectParameter("dt_ini", dt_ini) :
                new ObjectParameter("dt_ini", typeof(System.DateTime));
    
            var dt_fimParameter = dt_fim.HasValue ?
                new ObjectParameter("dt_fim", dt_fim) :
                new ObjectParameter("dt_fim", typeof(System.DateTime));
    
            var cdusuarioParameter = cdusuario.HasValue ?
                new ObjectParameter("cdusuario", cdusuario) :
                new ObjectParameter("cdusuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_extratoEMPRESA3lometros_Result>("sp_rel_extratoEMPRESA3lometros", dt_iniParameter, dt_fimParameter, cdusuarioParameter);
        }
    
        public virtual ObjectResult<sp_rel_FastCash_conc_pedidos_Result> sp_rel_FastCash_conc_pedidos(Nullable<int> situacao, Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal)
        {
            var situacaoParameter = situacao.HasValue ?
                new ObjectParameter("Situacao", situacao) :
                new ObjectParameter("Situacao", typeof(int));
    
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("DataInicial", dataInicial) :
                new ObjectParameter("DataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("DataFinal", dataFinal) :
                new ObjectParameter("DataFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_FastCash_conc_pedidos_Result>("sp_rel_FastCash_conc_pedidos", situacaoParameter, dataInicialParameter, dataFinalParameter);
        }
    
        public virtual ObjectResult<sp_rel_FastCash_conc_pedidos_cashIn_Result> sp_rel_FastCash_conc_pedidos_cashIn(Nullable<int> situacao, Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal)
        {
            var situacaoParameter = situacao.HasValue ?
                new ObjectParameter("Situacao", situacao) :
                new ObjectParameter("Situacao", typeof(int));
    
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("DataInicial", dataInicial) :
                new ObjectParameter("DataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("DataFinal", dataFinal) :
                new ObjectParameter("DataFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_FastCash_conc_pedidos_cashIn_Result>("sp_rel_FastCash_conc_pedidos_cashIn", situacaoParameter, dataInicialParameter, dataFinalParameter);
        }
    
        public virtual ObjectResult<sp_rel_EMPRESA3lometrosextrato_Result> sp_rel_EMPRESA3lometrosextrato(Nullable<System.DateTime> dt_ini, Nullable<System.DateTime> dt_fim, Nullable<int> cdusuario, Nullable<int> status)
        {
            var dt_iniParameter = dt_ini.HasValue ?
                new ObjectParameter("dt_ini", dt_ini) :
                new ObjectParameter("dt_ini", typeof(System.DateTime));
    
            var dt_fimParameter = dt_fim.HasValue ?
                new ObjectParameter("dt_fim", dt_fim) :
                new ObjectParameter("dt_fim", typeof(System.DateTime));
    
            var cdusuarioParameter = cdusuario.HasValue ?
                new ObjectParameter("cdusuario", cdusuario) :
                new ObjectParameter("cdusuario", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_EMPRESA3lometrosextrato_Result>("sp_rel_EMPRESA3lometrosextrato", dt_iniParameter, dt_fimParameter, cdusuarioParameter, statusParameter);
        }
    
        public virtual int sp_rel_Operacoes_por_tipo_pagamento(Nullable<int> cd_operadora, Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag)
        {
            var cd_operadoraParameter = cd_operadora.HasValue ?
                new ObjectParameter("cd_operadora", cd_operadora) :
                new ObjectParameter("cd_operadora", typeof(int));
    
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_rel_Operacoes_por_tipo_pagamento", cd_operadoraParameter, dt_ini_pagParameter, dt_fim_pagParameter);
        }
    
        public virtual ObjectResult<sp_rel_pedido_FastCash_arquivo_Result> sp_rel_pedido_FastCash_arquivo(Nullable<int> codigoPed, Nullable<System.DateTime> dateInitial, Nullable<System.DateTime> dateEnd, Nullable<long> cliEMPRESA3, Nullable<int> formaPag, Nullable<int> canal, Nullable<int> tempo, Nullable<int> comprovante)
        {
            var codigoPedParameter = codigoPed.HasValue ?
                new ObjectParameter("CodigoPed", codigoPed) :
                new ObjectParameter("CodigoPed", typeof(int));
    
            var dateInitialParameter = dateInitial.HasValue ?
                new ObjectParameter("dateInitial", dateInitial) :
                new ObjectParameter("dateInitial", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            var cliEMPRESA3Parameter = cliEMPRESA3.HasValue ?
                new ObjectParameter("CliEMPRESA3", cliEMPRESA3) :
                new ObjectParameter("CliEMPRESA3", typeof(long));
    
            var formaPagParameter = formaPag.HasValue ?
                new ObjectParameter("FormaPag", formaPag) :
                new ObjectParameter("FormaPag", typeof(int));
    
            var canalParameter = canal.HasValue ?
                new ObjectParameter("Canal", canal) :
                new ObjectParameter("Canal", typeof(int));
    
            var tempoParameter = tempo.HasValue ?
                new ObjectParameter("Tempo", tempo) :
                new ObjectParameter("Tempo", typeof(int));
    
            var comprovanteParameter = comprovante.HasValue ?
                new ObjectParameter("comprovante", comprovante) :
                new ObjectParameter("comprovante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_pedido_FastCash_arquivo_Result>("sp_rel_pedido_FastCash_arquivo", codigoPedParameter, dateInitialParameter, dateEndParameter, cliEMPRESA3Parameter, formaPagParameter, canalParameter, tempoParameter, comprovanteParameter);
        }
    
        public virtual ObjectResult<sp_rel_pedidos_doacoes_Result> sp_rel_pedidos_doacoes(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal, Nullable<int> statusPedido)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("DataInicial", dataInicial) :
                new ObjectParameter("DataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("DataFinal", dataFinal) :
                new ObjectParameter("DataFinal", typeof(System.DateTime));
    
            var statusPedidoParameter = statusPedido.HasValue ?
                new ObjectParameter("StatusPedido", statusPedido) :
                new ObjectParameter("StatusPedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_pedidos_doacoes_Result>("sp_rel_pedidos_doacoes", dataInicialParameter, dataFinalParameter, statusPedidoParameter);
        }
    
        public virtual ObjectResult<sp_rel_prestacao_contas_gateway_Result> sp_rel_prestacao_contas_gateway(Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag, Nullable<int> cd_forma_pagamento, Nullable<int> cd_gateway)
        {
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            var cd_forma_pagamentoParameter = cd_forma_pagamento.HasValue ?
                new ObjectParameter("cd_forma_pagamento", cd_forma_pagamento) :
                new ObjectParameter("cd_forma_pagamento", typeof(int));
    
            var cd_gatewayParameter = cd_gateway.HasValue ?
                new ObjectParameter("cd_gateway", cd_gateway) :
                new ObjectParameter("cd_gateway", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_prestacao_contas_gateway_Result>("sp_rel_prestacao_contas_gateway", dt_ini_pagParameter, dt_fim_pagParameter, cd_forma_pagamentoParameter, cd_gatewayParameter);
        }
    
        public virtual ObjectResult<sp_rel_prestacao_contas_operadora_Result> sp_rel_prestacao_contas_operadora(Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag, Nullable<int> cd_operadora, Nullable<bool> filtrarEstorno, Nullable<int> cd_empresa)
        {
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            var cd_operadoraParameter = cd_operadora.HasValue ?
                new ObjectParameter("cd_operadora", cd_operadora) :
                new ObjectParameter("cd_operadora", typeof(int));
    
            var filtrarEstornoParameter = filtrarEstorno.HasValue ?
                new ObjectParameter("filtrarEstorno", filtrarEstorno) :
                new ObjectParameter("filtrarEstorno", typeof(bool));
    
            var cd_empresaParameter = cd_empresa.HasValue ?
                new ObjectParameter("cd_empresa", cd_empresa) :
                new ObjectParameter("cd_empresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_prestacao_contas_operadora_Result>("sp_rel_prestacao_contas_operadora", dt_ini_pagParameter, dt_fim_pagParameter, cd_operadoraParameter, filtrarEstornoParameter, cd_empresaParameter);
        }
    
        public virtual ObjectResult<sp_rel_prestacao_contas_operadora_processado_Result> sp_rel_prestacao_contas_operadora_processado(Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag, Nullable<int> cd_operadora)
        {
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            var cd_operadoraParameter = cd_operadora.HasValue ?
                new ObjectParameter("cd_operadora", cd_operadora) :
                new ObjectParameter("cd_operadora", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_prestacao_contas_operadora_processado_Result>("sp_rel_prestacao_contas_operadora_processado", dt_ini_pagParameter, dt_fim_pagParameter, cd_operadoraParameter);
        }
    
        public virtual int sp_rel_recebimentos(Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag, Nullable<int> cd_operadora, Nullable<int> cd_empresa)
        {
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            var cd_operadoraParameter = cd_operadora.HasValue ?
                new ObjectParameter("cd_operadora", cd_operadora) :
                new ObjectParameter("cd_operadora", typeof(int));
    
            var cd_empresaParameter = cd_empresa.HasValue ?
                new ObjectParameter("cd_empresa", cd_empresa) :
                new ObjectParameter("cd_empresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_rel_recebimentos", dt_ini_pagParameter, dt_fim_pagParameter, cd_operadoraParameter, cd_empresaParameter);
        }
    
        public virtual int sp_rel_recebimentos_cash_in(Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag)
        {
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_rel_recebimentos_cash_in", dt_ini_pagParameter, dt_fim_pagParameter);
        }
    
        public virtual int sp_rel_recebimentos_celular_serv_digitais(Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag)
        {
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_rel_recebimentos_celular_serv_digitais", dt_ini_pagParameter, dt_fim_pagParameter);
        }
    
        public virtual int sp_rel_recebimentos_rv(Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag)
        {
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_rel_recebimentos_rv", dt_ini_pagParameter, dt_fim_pagParameter);
        }
    
        public virtual ObjectResult<sp_rel_revenda_vendas_por_revendedor_Result> sp_rel_revenda_vendas_por_revendedor(Nullable<System.DateTime> dt_ini, Nullable<System.DateTime> dt_fim, Nullable<int> cd_usuario, Nullable<int> cd_status_pedido)
        {
            var dt_iniParameter = dt_ini.HasValue ?
                new ObjectParameter("dt_ini", dt_ini) :
                new ObjectParameter("dt_ini", typeof(System.DateTime));
    
            var dt_fimParameter = dt_fim.HasValue ?
                new ObjectParameter("dt_fim", dt_fim) :
                new ObjectParameter("dt_fim", typeof(System.DateTime));
    
            var cd_usuarioParameter = cd_usuario.HasValue ?
                new ObjectParameter("cd_usuario", cd_usuario) :
                new ObjectParameter("cd_usuario", typeof(int));
    
            var cd_status_pedidoParameter = cd_status_pedido.HasValue ?
                new ObjectParameter("cd_status_pedido", cd_status_pedido) :
                new ObjectParameter("cd_status_pedido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_rel_revenda_vendas_por_revendedor_Result>("sp_rel_revenda_vendas_por_revendedor", dt_iniParameter, dt_fimParameter, cd_usuarioParameter, cd_status_pedidoParameter);
        }
    
        public virtual int sp_rel_TransacoesDiariasPagas(Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag)
        {
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_rel_TransacoesDiariasPagas", dt_ini_pagParameter, dt_fim_pagParameter);
        }
    
        public virtual int sp_rel_vendas(Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag, Nullable<short> tp_pedido_item, Nullable<int> cd_empresa)
        {
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            var tp_pedido_itemParameter = tp_pedido_item.HasValue ?
                new ObjectParameter("tp_pedido_item", tp_pedido_item) :
                new ObjectParameter("tp_pedido_item", typeof(short));
    
            var cd_empresaParameter = cd_empresa.HasValue ?
                new ObjectParameter("cd_empresa", cd_empresa) :
                new ObjectParameter("cd_empresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_rel_vendas", dt_ini_pagParameter, dt_fim_pagParameter, tp_pedido_itemParameter, cd_empresaParameter);
        }
    
        public virtual int sp_rel_vendas_transporte(Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag, Nullable<short> tp_pedido_item)
        {
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            var tp_pedido_itemParameter = tp_pedido_item.HasValue ?
                new ObjectParameter("tp_pedido_item", tp_pedido_item) :
                new ObjectParameter("tp_pedido_item", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_rel_vendas_transporte", dt_ini_pagParameter, dt_fim_pagParameter, tp_pedido_itemParameter);
        }
    
        public virtual ObjectResult<sp_relatorio_relacionamento_Result> sp_relatorio_relacionamento(Nullable<int> perfil, Nullable<int> atendente, Nullable<int> origem, Nullable<int> motivo, Nullable<long> usuario, string cpf, string cnpj, Nullable<int> situacao, Nullable<long> pedido, Nullable<System.DateTime> dt_ini, Nullable<System.DateTime> dt_fim, string cd_protocolo)
        {
            var perfilParameter = perfil.HasValue ?
                new ObjectParameter("perfil", perfil) :
                new ObjectParameter("perfil", typeof(int));
    
            var atendenteParameter = atendente.HasValue ?
                new ObjectParameter("atendente", atendente) :
                new ObjectParameter("atendente", typeof(int));
    
            var origemParameter = origem.HasValue ?
                new ObjectParameter("origem", origem) :
                new ObjectParameter("origem", typeof(int));
    
            var motivoParameter = motivo.HasValue ?
                new ObjectParameter("motivo", motivo) :
                new ObjectParameter("motivo", typeof(int));
    
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(long));
    
            var cpfParameter = cpf != null ?
                new ObjectParameter("cpf", cpf) :
                new ObjectParameter("cpf", typeof(string));
    
            var cnpjParameter = cnpj != null ?
                new ObjectParameter("cnpj", cnpj) :
                new ObjectParameter("cnpj", typeof(string));
    
            var situacaoParameter = situacao.HasValue ?
                new ObjectParameter("situacao", situacao) :
                new ObjectParameter("situacao", typeof(int));
    
            var pedidoParameter = pedido.HasValue ?
                new ObjectParameter("pedido", pedido) :
                new ObjectParameter("pedido", typeof(long));
    
            var dt_iniParameter = dt_ini.HasValue ?
                new ObjectParameter("dt_ini", dt_ini) :
                new ObjectParameter("dt_ini", typeof(System.DateTime));
    
            var dt_fimParameter = dt_fim.HasValue ?
                new ObjectParameter("dt_fim", dt_fim) :
                new ObjectParameter("dt_fim", typeof(System.DateTime));
    
            var cd_protocoloParameter = cd_protocolo != null ?
                new ObjectParameter("cd_protocolo", cd_protocolo) :
                new ObjectParameter("cd_protocolo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_relatorio_relacionamento_Result>("sp_relatorio_relacionamento", perfilParameter, atendenteParameter, origemParameter, motivoParameter, usuarioParameter, cpfParameter, cnpjParameter, situacaoParameter, pedidoParameter, dt_iniParameter, dt_fimParameter, cd_protocoloParameter);
        }
    
        public virtual ObjectResult<sp_remessa_api_itau_Result> sp_remessa_api_itau(Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal)
        {
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("dataInicial", dataInicial) :
                new ObjectParameter("dataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("dataFinal", dataFinal) :
                new ObjectParameter("dataFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_remessa_api_itau_Result>("sp_remessa_api_itau", dataInicialParameter, dataFinalParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_searchReversal_Result> sp_searchReversal(Nullable<System.DateTime> dt_ini_pag, Nullable<System.DateTime> dt_fim_pag)
        {
            var dt_ini_pagParameter = dt_ini_pag.HasValue ?
                new ObjectParameter("dt_ini_pag", dt_ini_pag) :
                new ObjectParameter("dt_ini_pag", typeof(System.DateTime));
    
            var dt_fim_pagParameter = dt_fim_pag.HasValue ?
                new ObjectParameter("dt_fim_pag", dt_fim_pag) :
                new ObjectParameter("dt_fim_pag", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_searchReversal_Result>("sp_searchReversal", dt_ini_pagParameter, dt_fim_pagParameter);
        }
    
        public virtual int sp_ultima_execucao_servico(Nullable<int> cd_servico)
        {
            var cd_servicoParameter = cd_servico.HasValue ?
                new ObjectParameter("cd_servico", cd_servico) :
                new ObjectParameter("cd_servico", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ultima_execucao_servico", cd_servicoParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<sp_usuario_saldo_Result> sp_usuario_saldo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_usuario_saldo_Result>("sp_usuario_saldo");
        }
    
        public virtual ObjectResult<sp_verifica_sessao_termo_uso_Result> sp_verifica_sessao_termo_uso(Nullable<long> usuario, Nullable<short> ic_EMPRESA3ais, Nullable<short> ic_Revenda)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(long));
    
            var ic_EMPRESA3aisParameter = ic_EMPRESA3ais.HasValue ?
                new ObjectParameter("ic_EMPRESA3ais", ic_EMPRESA3ais) :
                new ObjectParameter("ic_EMPRESA3ais", typeof(short));
    
            var ic_RevendaParameter = ic_Revenda.HasValue ?
                new ObjectParameter("ic_Revenda", ic_Revenda) :
                new ObjectParameter("ic_Revenda", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_verifica_sessao_termo_uso_Result>("sp_verifica_sessao_termo_uso", usuarioParameter, ic_EMPRESA3aisParameter, ic_RevendaParameter);
        }
    
        public virtual ObjectResult<sp_verifica_sessao_termo_uso_fidelidade_Result> sp_verifica_sessao_termo_uso_fidelidade(Nullable<long> usuario)
        {
            var usuarioParameter = usuario.HasValue ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_verifica_sessao_termo_uso_fidelidade_Result>("sp_verifica_sessao_termo_uso_fidelidade", usuarioParameter);
        }
    }
}
