//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_aux_developer_operadora
    {
        public int cd_aux_developer_operadora { get; set; }
        public Nullable<int> cd_operadora { get; set; }
        public string tipo_servico { get; set; }
        public Nullable<bool> ic_validar { get; set; }
    }
}
