//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_analise_spd_conta
    {
        public int cd_analise_spd_conta { get; set; }
        public Nullable<int> id_status { get; set; }
        public string ds_name { get; set; }
        public Nullable<int> id_reason { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<long> cd_usuario_banco_conta { get; set; }
    
        public virtual tb_usuario_banco_conta tb_usuario_banco_conta { get; set; }
    }
}
