//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_api_copa
    {
        public int cd_api_copa { get; set; }
        public Nullable<int> cd_campeonato { get; set; }
        public Nullable<int> cd_fase { get; set; }
        public string ds_retorno { get; set; }
    }
}
