//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_boleto
    {
        public long cd_boleto { get; set; }
        public long cd_pedido { get; set; }
        public int cd_conta { get; set; }
        public string nu_nosso_numero { get; set; }
        public decimal vl_pedido { get; set; }
        public decimal vl_taxa { get; set; }
        public decimal vl_total_boleto { get; set; }
        public System.DateTime dt_vencimento { get; set; }
        public string ds_linha_digitavel { get; set; }
        public string ds_codigo_barras { get; set; }
        public string ds_boleto_html { get; set; }
        public Nullable<int> cd_remessa_cobranca { get; set; }
        public Nullable<int> cd_remessa_cobranca_cancelamento { get; set; }
        public string ds_api_reg_envio { get; set; }
        public string ds_api_reg_retorno { get; set; }
    
        public virtual tb_conta tb_conta { get; set; }
        public virtual tb_pedido tb_pedido { get; set; }
        public virtual tb_remessa_cobranca tb_remessa_cobranca { get; set; }
    }
}
