//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_banner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_banner()
        {
            this.tb_pagina_cupom = new HashSet<tb_pagina_cupom>();
        }
    
        public int cd_banner { get; set; }
        public string ds_banner { get; set; }
        public string lst_operadora { get; set; }
        public Nullable<int> cd_acao { get; set; }
        public Nullable<System.DateTime> dt_inicio { get; set; }
        public Nullable<System.DateTime> dt_validade { get; set; }
        public Nullable<bool> ic_ativo { get; set; }
        public string ds_link_banner { get; set; }
        public string ds_link_acao { get; set; }
        public Nullable<bool> ic_prioritario { get; set; }
    
        public virtual tb_acao_banner tb_acao_banner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pagina_cupom> tb_pagina_cupom { get; set; }
    }
}
