//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_banco_conta_digital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_banco_conta_digital()
        {
            this.tb_tipo_transacao = new HashSet<tb_tipo_transacao>();
            this.tb_transacao_conta_digital = new HashSet<tb_transacao_conta_digital>();
        }
    
        public int cd_banco_conta_digital { get; set; }
        public string nm_banco_conta_digital { get; set; }
        public Nullable<bool> ic_inativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_tipo_transacao> tb_tipo_transacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_transacao_conta_digital> tb_transacao_conta_digital { get; set; }
    }
}
