//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_black_list
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_black_list()
        {
            this.tb_black_list_usuario_forma_pagamento = new HashSet<tb_black_list_usuario_forma_pagamento>();
        }
    
        public int cd_black_list { get; set; }
        public string nu_cpf_usuario { get; set; }
        public string ds_email_usuario { get; set; }
        public Nullable<int> cd_tipo_cartao { get; set; }
        public string nu_cartao { get; set; }
        public Nullable<System.DateTime> dt_inclusao_black_list { get; set; }
        public Nullable<int> cd_usuario_adm { get; set; }
    
        public virtual tb_tipo_cartao tb_tipo_cartao { get; set; }
        public virtual tb_usuario_adm tb_usuario_adm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_black_list_usuario_forma_pagamento> tb_black_list_usuario_forma_pagamento { get; set; }
    }
}
