//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_controle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_controle()
        {
            this.tb_pagina_controle = new HashSet<tb_pagina_controle>();
        }
    
        public int cd_controle { get; set; }
        public Nullable<int> cd_tipo_controle { get; set; }
        public string ds_descricao { get; set; }
        public string ds_titulo_controle { get; set; }
        public string ds_cor_fundo_controle { get; set; }
        public string ds_valor_texto { get; set; }
        public string ds_cor_texto { get; set; }
        public Nullable<bool> ic_bold_texto { get; set; }
        public Nullable<int> nu_tamanho_texto { get; set; }
        public Nullable<int> nu_largura { get; set; }
        public Nullable<int> nu_altura { get; set; }
        public string ds_align { get; set; }
        public string ds_link { get; set; }
        public string ds_deeplink { get; set; }
    
        public virtual tb_tipo_controle tb_tipo_controle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pagina_controle> tb_pagina_controle { get; set; }
    }
}
