//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_crm_relacionamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_crm_relacionamento()
        {
            this.tb_crm_relacionamento_usr_atribuido = new HashSet<tb_crm_relacionamento_usr_atribuido>();
            this.tb_crm_relacionamento_arquivos = new HashSet<tb_crm_relacionamento_arquivos>();
        }
    
        public decimal cd_relacionamento { get; set; }
        public long cd_usuario { get; set; }
        public Nullable<System.DateTime> dt_inicio_relacionamento { get; set; }
        public Nullable<System.DateTime> dt_fim_relacionamento { get; set; }
        public string ds_nota { get; set; }
        public short cd_motivo_relacionamento { get; set; }
        public Nullable<short> cd_situacao_relacionamento { get; set; }
        public Nullable<short> cd_tipo_relacionamento { get; set; }
        public Nullable<int> cd_usuario_adm { get; set; }
        public Nullable<short> nu_prioridade { get; set; }
        public string cd_protocolo { get; set; }
        public string ds_protocolo_externo { get; set; }
        public Nullable<int> cd_num_pedido { get; set; }
        public Nullable<int> cd_tipo { get; set; }
        public string nu_pedido_cash_in { get; set; }
    
        public virtual tb_crm_motivo_relacionamento tb_crm_motivo_relacionamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_crm_relacionamento_usr_atribuido> tb_crm_relacionamento_usr_atribuido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_crm_relacionamento_arquivos> tb_crm_relacionamento_arquivos { get; set; }
        public virtual tb_crm_situacao_relacionamento tb_crm_situacao_relacionamento { get; set; }
        public virtual tb_crm_tipo_relacionamento tb_crm_tipo_relacionamento { get; set; }
        public virtual tb_usuario_adm tb_usuario_adm { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
