//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cartao_tarifa_sptrans
    {
        public int cd_cartao_tarifa_sptrans { get; set; }
        public Nullable<int> nu_cartao { get; set; }
        public Nullable<int> cd_tarifa { get; set; }
    }
}
