//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_campanha
    {
        public long cd_campanha { get; set; }
        public string ds_nome_usuario { get; set; }
        public string nu_tel_usuario { get; set; }
        public string ds_email_usuario { get; set; }
        public System.DateTime dt_registro { get; set; }
    }
}
