//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cupom_oferta
    {
        public long cd_cupom_oferta { get; set; }
        public string ds_cupom_oferta { get; set; }
        public string ds_codigo { get; set; }
        public Nullable<decimal> vl_desconto { get; set; }
        public long cd_cupom_loja { get; set; }
        public long cd_categoria_cupom_loja { get; set; }
        public string dt_vigencia { get; set; }
        public string lnk_cupom_oferta { get; set; }
        public Nullable<bool> ic_cupom_oferta_novo { get; set; }
        public Nullable<bool> ic_top_cupom_oferta { get; set; }
        public Nullable<bool> ic_exibir_cupom_oferta { get; set; }
    
        public virtual tb_cupom_categoria_loja tb_cupom_categoria_loja { get; set; }
        public virtual tb_cupom_loja tb_cupom_loja { get; set; }
    }
}
