//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_crm_relacionamento_usr_atribuido
    {
        public long cd_crm_relacionamento_usr_atribuido { get; set; }
        public string ds_nota { get; set; }
        public int cd_usuario_adm_atr { get; set; }
        public int cd_usuario_adm { get; set; }
        public System.DateTime dt_usuario_adm_atr_crt { get; set; }
        public decimal cd_relacionamento { get; set; }
        public bool ic_atr_show { get; set; }
        public short cd_crm_situacao_situacao_relacionamento_usr_atribuido { get; set; }
        public Nullable<System.DateTime> dt_atr_edt_ini { get; set; }
        public Nullable<System.DateTime> dt_atr_edt_fim { get; set; }
    
        public virtual tb_crm_relacionamento tb_crm_relacionamento { get; set; }
        public virtual tb_crm_situacao_relacionamento_usr_atribuido tb_crm_situacao_relacionamento_usr_atribuido { get; set; }
        public virtual tb_usuario_adm tb_usuario_adm { get; set; }
        public virtual tb_usuario_adm tb_usuario_adm1 { get; set; }
    }
}
