//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cidade()
        {
            this.tb_operadora_cidade = new HashSet<tb_operadora_cidade>();
        }
    
        public int cd_cidade { get; set; }
        public string nm_cidade { get; set; }
        public decimal nu_latitude { get; set; }
        public decimal nu_longitude { get; set; }
        public short cd_uf { get; set; }
        public Nullable<int> nu_raio { get; set; }
    
        public virtual tb_uf tb_uf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_operadora_cidade> tb_operadora_cidade { get; set; }
    }
}
