//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_canal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_canal()
        {
            this.tb_pedido = new HashSet<tb_pedido>();
            this.tb_usuario = new HashSet<tb_usuario>();
        }
    
        public short cd_canal { get; set; }
        public string ds_canal { get; set; }
        public bool ic_canal_inativo { get; set; }
        public bool ic_EMPRESA3mais { get; set; }
        public Nullable<int> cd_tipo_canal { get; set; }
        public Nullable<bool> ic_aprovado { get; set; }
        public Nullable<System.DateTime> dt_cadastro { get; set; }
    
        public virtual tb_tipo_canal tb_tipo_canal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido> tb_pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuario> tb_usuario { get; set; }
    }
}
