//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_crm_relacionamento_arquivos
    {
        public decimal cd_relacionamento_arquivo { get; set; }
        public Nullable<decimal> cd_relacionamento { get; set; }
        public string ds_nome_arquivo { get; set; }
        public Nullable<int> cd_usuario_adm { get; set; }
        public Nullable<System.DateTime> dt_arquivo { get; set; }
        public string ds_arquivo_binary { get; set; }
    
        public virtual tb_crm_relacionamento tb_crm_relacionamento { get; set; }
    }
}
