//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_conta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_conta()
        {
            this.tb_boleto = new HashSet<tb_boleto>();
        }
    
        public int cd_conta { get; set; }
        public string ds_conta { get; set; }
        public Nullable<int> cd_banco { get; set; }
        public Nullable<short> cd_instrucao_boleto { get; set; }
        public string ds_age_num { get; set; }
        public string ds_age_num_dv { get; set; }
        public string ds_num_conta { get; set; }
        public string ds_num_conta_dv { get; set; }
        public string ds_codigo_cedente { get; set; }
        public string ds_nossonumero { get; set; }
        public string ds_cod_conve_remessa { get; set; }
        public Nullable<int> nu_remessa { get; set; }
        public Nullable<bool> ic_boleto_registro { get; set; }
        public Nullable<int> nu_remessa_cobranca { get; set; }
        public Nullable<bool> ic_impressao_boleto { get; set; }
        public Nullable<bool> ic_inativo { get; set; }
        public string nu_api_bol_client_id { get; set; }
        public string ds_api_bol_client_chave { get; set; }
        public string ds_api_bol_client_secret { get; set; }
        public string ds_api_url_token { get; set; }
        public string ds_api_url_registro_boleto { get; set; }
        public Nullable<bool> ic_EMPRESA3mais { get; set; }
        public string nu_cnpj_favorecido { get; set; }
        public Nullable<bool> ic_cash_in { get; set; }
    
        public virtual tb_banco tb_banco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_boleto> tb_boleto { get; set; }
        public virtual tb_instrucao_boleto tb_instrucao_boleto { get; set; }
    }
}
