//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_crm_situacao_relacionamento_usr_atribuido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_crm_situacao_relacionamento_usr_atribuido()
        {
            this.tb_crm_relacionamento_usr_atribuido = new HashSet<tb_crm_relacionamento_usr_atribuido>();
        }
    
        public short cd_crm_situacao_situacao_relacionamento_usr_atribuido { get; set; }
        public string ds_situacao { get; set; }
        public Nullable<bool> ic_crm_situacao_situacao_relacionamento_usr_atribuido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_crm_relacionamento_usr_atribuido> tb_crm_relacionamento_usr_atribuido { get; set; }
    }
}
