//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cupom_loja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cupom_loja()
        {
            this.tb_cupom_oferta = new HashSet<tb_cupom_oferta>();
        }
    
        public long cd_cupom_loja { get; set; }
        public string ds_loja_cupom_nome { get; set; }
        public string img_cupom_loja { get; set; }
        public string lnk_cupom_loja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_cupom_oferta> tb_cupom_oferta { get; set; }
    }
}
