//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_estorno_pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_estorno_pedido()
        {
            this.tb_estorno_pedido_item = new HashSet<tb_estorno_pedido_item>();
        }
    
        public int cd_estorno_pedido { get; set; }
        public long cd_pedido { get; set; }
        public System.DateTime dt_solicitacao_inicio { get; set; }
        public int cd_usuario_adm_solicitacao { get; set; }
        public string ds_motivo_estorno { get; set; }
        public Nullable<System.DateTime> dt_solicitacao_fim { get; set; }
        public Nullable<int> cd_usuario_adm_fim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_estorno_pedido_item> tb_estorno_pedido_item { get; set; }
        public virtual tb_pedido tb_pedido { get; set; }
        public virtual tb_usuario_adm tb_usuario_adm { get; set; }
        public virtual tb_usuario_adm tb_usuario_adm1 { get; set; }
    }
}
