//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_estudante_serie
    {
        public int cd_serie { get; set; }
        public string ds_serie { get; set; }
        public Nullable<bool> ic_ativo { get; set; }
        public Nullable<int> cd_operadora { get; set; }
    }
}
