//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_etapa_status_via
    {
        public int cd_etapa_status_via { get; set; }
        public Nullable<int> cd_etapa_via { get; set; }
        public Nullable<int> cd_status_etapa_finalizada { get; set; }
    }
}
