//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_estudante_complemento
    {
        public long cd_estudante_complemento { get; set; }
        public Nullable<long> cd_requisicao { get; set; }
        public Nullable<int> cd_titular { get; set; }
        public string ds_titular { get; set; }
        public Nullable<int> cd_instituicao { get; set; }
        public string ds_instituicao { get; set; }
        public Nullable<int> cd_grau { get; set; }
        public Nullable<int> cd_serie { get; set; }
        public Nullable<int> cd_turno { get; set; }
        public string nu_carteira_estudante { get; set; }
        public string cd_tarifa { get; set; }
        public string ds_tarifa { get; set; }
        public Nullable<decimal> vl_tarifa { get; set; }
        public Nullable<int> qt_tarifa { get; set; }
        public string cd_tarifa2 { get; set; }
        public string ds_tarifa2 { get; set; }
        public Nullable<decimal> vl_tarifa2 { get; set; }
        public Nullable<int> qt_tarifa2 { get; set; }
        public string cd_tarifa3 { get; set; }
        public string ds_tarifa3 { get; set; }
        public Nullable<decimal> vl_tarifa3 { get; set; }
        public Nullable<int> qt_tarifa3 { get; set; }
        public string cd_tarifa4 { get; set; }
        public string ds_tarifa4 { get; set; }
        public Nullable<decimal> vl_tarifa4 { get; set; }
        public Nullable<int> qt_tarifa4 { get; set; }
    }
}
