//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_erro_sistema
    {
        public int cd_erro_sistema { get; set; }
        public System.DateTime dt_erro_sistema { get; set; }
        public string ds_erro_sistema { get; set; }
        public string ds_trace_erro_sistema { get; set; }
        public string nm_classe { get; set; }
        public string nm_operacao { get; set; }
        public string ds_body { get; set; }
        public Nullable<long> cd_usuario { get; set; }
        public Nullable<int> cd_operadora { get; set; }
        public Nullable<long> cd_pedido { get; set; }
    }
}
