//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_estorno_pedido_item
    {
        public int cd_estorno_pedido_item { get; set; }
        public int cd_estorno_pedido { get; set; }
        public long cd_pedido_item { get; set; }
        public decimal vl_original { get; set; }
        public Nullable<decimal> vl_estorno { get; set; }
        public Nullable<int> nu_carga_operadora { get; set; }
    
        public virtual tb_estorno_pedido tb_estorno_pedido { get; set; }
        public virtual tb_pedido_item tb_pedido_item { get; set; }
    }
}
