//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_erro_abertura_conta
    {
        public int cd_erro_abertura_conta { get; set; }
        public string ds_erro_abertura_conta { get; set; }
        public bool ic_permite_envio_dados { get; set; }
        public bool ic_inativo { get; set; }
    }
}
