//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fila_analise_revalidacao
    {
        public long cd_fila_analise_revalidacao { get; set; }
        public long cd_pedido { get; set; }
        public System.DateTime dt_registro { get; set; }
        public short cd_status { get; set; }
        public Nullable<System.DateTime> dt_finalizado { get; set; }
        public Nullable<int> cd_usuario_adm_finalizado { get; set; }
    
        public virtual tb_pedido tb_pedido { get; set; }
        public virtual tb_usuario_adm tb_usuario_adm { get; set; }
    }
}
