//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fila_envio_email
    {
        public long cd_fila_envio_email { get; set; }
        public Nullable<long> cd_pedido { get; set; }
        public Nullable<long> cd_usuario { get; set; }
        public string ds_email_destino { get; set; }
        public string ds_assunto { get; set; }
        public string ds_body { get; set; }
        public Nullable<bool> ic_enviado { get; set; }
        public Nullable<System.DateTime> dt_envio { get; set; }
        public string ds_caminho_boleto { get; set; }
    }
}
