//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_faq
    {
        public int cd_faq { get; set; }
        public int nu_ordem { get; set; }
        public string ds_pergunta { get; set; }
        public string ds_resposta { get; set; }
        public bool ic_inativo { get; set; }
        public Nullable<int> cd_operadora { get; set; }
    
        public virtual tb_operadora tb_operadora { get; set; }
    }
}
