//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_forma_pagamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_forma_pagamento()
        {
            this.tb_black_list_usuario_forma_pagamento = new HashSet<tb_black_list_usuario_forma_pagamento>();
            this.tb_log_black_list_usuario_forma_pagamento = new HashSet<tb_log_black_list_usuario_forma_pagamento>();
            this.tb_operadora_forma_pagamento_gateway = new HashSet<tb_operadora_forma_pagamento_gateway>();
            this.tb_parametro_cashback = new HashSet<tb_parametro_cashback>();
            this.tb_pedido_cash_in = new HashSet<tb_pedido_cash_in>();
            this.tb_pedido = new HashSet<tb_pedido>();
            this.tb_taxa_adm = new HashSet<tb_taxa_adm>();
            this.tb_taxa_operadora_tipo_cartao = new HashSet<tb_taxa_operadora_tipo_cartao>();
            this.tb_tipo_cartao_forma_pagamento = new HashSet<tb_tipo_cartao_forma_pagamento>();
        }
    
        public short cd_forma_pagamento { get; set; }
        public string nm_descricao { get; set; }
        public short cd_gateway { get; set; }
        public bool ic_forma_pagamento_inativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_black_list_usuario_forma_pagamento> tb_black_list_usuario_forma_pagamento { get; set; }
        public virtual tb_gateway tb_gateway { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_log_black_list_usuario_forma_pagamento> tb_log_black_list_usuario_forma_pagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_operadora_forma_pagamento_gateway> tb_operadora_forma_pagamento_gateway { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_parametro_cashback> tb_parametro_cashback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_cash_in> tb_pedido_cash_in { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido> tb_pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_taxa_adm> tb_taxa_adm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_taxa_operadora_tipo_cartao> tb_taxa_operadora_tipo_cartao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_tipo_cartao_forma_pagamento> tb_tipo_cartao_forma_pagamento { get; set; }
    }
}
