//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_formulario_pergunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_formulario_pergunta()
        {
            this.tb_formulario_resposta_usuario = new HashSet<tb_formulario_resposta_usuario>();
        }
    
        public int cd_formulario_pergunta { get; set; }
        public short tp_assunto_formulario_pergunta { get; set; }
        public string ds_formulario_pergunta { get; set; }
        public bool ic_formulario_pergunta_aberta { get; set; }
        public bool ic_formulario_pergunta_inativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_formulario_resposta_usuario> tb_formulario_resposta_usuario { get; set; }
    }
}
