//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fastcash_phill
    {
        public int cd_log_fastcash_phill { get; set; }
        public string cd_pedido { get; set; }
        public string ds_descricao { get; set; }
        public Nullable<System.DateTime> dt_log { get; set; }
    }
}
