//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fluxo_etapa_via
    {
        public int cd_fluxo_etapa_via { get; set; }
        public Nullable<int> cd_operadora { get; set; }
        public Nullable<int> tp_requisicao { get; set; }
        public Nullable<int> nu_ordem { get; set; }
        public Nullable<int> cd_etapa_via { get; set; }
    
        public virtual tb_etapa_via tb_etapa_via { get; set; }
    }
}
