//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ged_pedido
    {
        public long cd_ged_pedido { get; set; }
        public long cd_pedido { get; set; }
        public byte[] ds_imagem_binary { get; set; }
        public System.DateTime dt_registro { get; set; }
    
        public virtual tb_pedido tb_pedido { get; set; }
    }
}
