//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_historico_requisicao_via
    {
        public long cd_historico_requisicao_via { get; set; }
        public Nullable<long> cd_requisicao_via { get; set; }
        public Nullable<System.DateTime> dt_historico { get; set; }
        public Nullable<int> cd_status_requisicao { get; set; }
        public string ds_observacao { get; set; }
    
        public virtual tb_requisicao_via tb_requisicao_via { get; set; }
    }
}
