//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_instrucao_boleto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_instrucao_boleto()
        {
            this.tb_conta = new HashSet<tb_conta>();
        }
    
        public short cd_instrucao_boleto { get; set; }
        public string ds_nome { get; set; }
        public string ds_inf_superior { get; set; }
        public string ds_inf_meio { get; set; }
        public string ds_inf_inferior { get; set; }
        public Nullable<bool> ic_inativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_conta> tb_conta { get; set; }
    }
}
