//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_integracao_parametro_notificacao
    {
        public int cd_integracao_parametro_notificacao { get; set; }
        public Nullable<int> cd_integracao { get; set; }
        public string ds_email { get; set; }
        public string ds_telefone { get; set; }
    }
}
