//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_integracao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_integracao()
        {
            this.tb_integracao_historico = new HashSet<tb_integracao_historico>();
        }
    
        public int cd_integracao { get; set; }
        public string ds_nome_integracao { get; set; }
        public string ds_link_externo { get; set; }
        public string ds_endereco_servidor { get; set; }
        public string ds_token { get; set; }
        public string ds_usuario { get; set; }
        public string ds_senha { get; set; }
        public Nullable<System.DateTime> dt_ultimo_sucesso { get; set; }
        public Nullable<bool> ic_alerta_amarelo { get; set; }
        public Nullable<bool> ic_alerta_vermelho { get; set; }
        public string ds_cabecalho { get; set; }
        public string ds_tipo { get; set; }
        public string ds_body { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_integracao_historico> tb_integracao_historico { get; set; }
    }
}
