//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_importacao_adyen
    {
        public int cd_importacao_adyen { get; set; }
        public System.DateTime dt_importacao { get; set; }
        public string nm_arquivo_importacao { get; set; }
        public System.DateTime dt_arquivo { get; set; }
        public string CompanyAccount { get; set; }
        public string MerchantAccount { get; set; }
        public string PspReference { get; set; }
        public Nullable<int> MerchantReference { get; set; }
        public string PaymentMethod { get; set; }
        public string CreationDate { get; set; }
        public string TimeZone { get; set; }
        public string TypeSeler { get; set; }
        public string ModificationReference { get; set; }
        public string GrossCurrency { get; set; }
        public Nullable<decimal> GrossDebitGC { get; set; }
        public Nullable<decimal> GrossCreditGC { get; set; }
        public string ExchangeRate { get; set; }
        public string NetCurrency { get; set; }
        public Nullable<decimal> NetDebitNC { get; set; }
        public Nullable<decimal> NetCreditNC { get; set; }
        public Nullable<decimal> CommissionNC { get; set; }
        public Nullable<decimal> MarkupNC { get; set; }
        public Nullable<decimal> SchemeFeesNC { get; set; }
        public Nullable<decimal> InterchangeNC { get; set; }
        public Nullable<decimal> AdvancedNC { get; set; }
        public string AdvancementCode { get; set; }
        public string AdvancementBatch { get; set; }
        public string PaymentMethodVariant { get; set; }
        public Nullable<int> BatchNumber { get; set; }
        public string Reserved4 { get; set; }
        public string Reserved5 { get; set; }
        public string Reserved6 { get; set; }
        public string Reserved7 { get; set; }
        public string Reserved8 { get; set; }
        public string Reserved9 { get; set; }
        public string Reserved10 { get; set; }
        public string Acquirer { get; set; }
        public string ModificationMerchantReference { get; set; }
        public string BookingDate { get; set; }
        public string BookingDateTimeZone { get; set; }
        public string AdditionalType { get; set; }
        public string Installments { get; set; }
        public string IssuerCountry { get; set; }
        public string ShopperCountry { get; set; }
        public string MerchantOrderReference { get; set; }
        public string MainCurrency { get; set; }
        public Nullable<decimal> MainAmount { get; set; }
        public string RecordType { get; set; }
        public string PaymentCurrency { get; set; }
        public Nullable<decimal> ReceivedPC { get; set; }
        public Nullable<decimal> AuthorisedPC { get; set; }
        public Nullable<decimal> CapturedPC { get; set; }
        public string SettlementCurrency { get; set; }
        public Nullable<decimal> PayableSC { get; set; }
        public Nullable<decimal> CommissionSC { get; set; }
        public Nullable<decimal> MarkupSC { get; set; }
        public Nullable<decimal> SchemeFeesSC { get; set; }
        public Nullable<decimal> InterchangeSC { get; set; }
        public string ProcessingFeeCurrency { get; set; }
        public Nullable<decimal> ProcessingFeeFC { get; set; }
        public string UserName { get; set; }
        public string SettlementBatch { get; set; }
        public Nullable<int> UniqueTerminalId { get; set; }
        public string PayableBookingDate { get; set; }
        public string PayoutDate { get; set; }
        public Nullable<decimal> InstallmentsPC { get; set; }
    }
}
