//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_EMPRESA3lometros_integracoes_diarias
    {
        public long cd_integracao_diaria { get; set; }
        public Nullable<long> cd_usuario_cartao { get; set; }
        public Nullable<System.DateTime> dt_integracao { get; set; }
        public Nullable<int> nu_integracoes_dia { get; set; }
    }
}
