//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_EMPRESA3lometros_config
    {
        public int cd_codigo { get; set; }
        public int vl_valor_conversao { get; set; }
        public Nullable<decimal> vl_valor_bonus { get; set; }
        public Nullable<int> vl_creditos_utilizacao { get; set; }
        public Nullable<System.DateTime> dt_ultima_exec { get; set; }
        public Nullable<short> qt_dias { get; set; }
    }
}
