//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_EMPRESA3lometros_expirados
    {
        public long cd_EMPRESA3lometros_expirado { get; set; }
        public Nullable<int> qt_pontos_expirados { get; set; }
        public Nullable<System.DateTime> dt_data_expiracao { get; set; }
        public Nullable<long> cd_usuario { get; set; }
    }
}
