//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_log_erro_abertura_conta
    {
        public int cd_log_erro_abertura_conta { get; set; }
        public Nullable<int> cd_usuario { get; set; }
        public Nullable<int> cd_erro_abertura_conta { get; set; }
        public Nullable<System.DateTime> dt_log { get; set; }
        public Nullable<bool> ic_ultimo_log { get; set; }
    }
}
