//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_linha_itinerario
    {
        public int cd_linha_itinerario { get; set; }
        public string id_linha_sbe { get; set; }
        public string id_itinerario { get; set; }
        public Nullable<int> cd_operadora { get; set; }
        public Nullable<System.DateTime> dt_atualizacao { get; set; }
    }
}
