//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_log_pedido_item_cancelamento_rv
    {
        public long cd_log_cancelamento_rv { get; set; }
        public long cd_pedido_item { get; set; }
        public int cd_usuario_adm { get; set; }
        public System.DateTime dt_cancelamento { get; set; }
        public string ds_log { get; set; }
    
        public virtual tb_pedido_item tb_pedido_item { get; set; }
        public virtual tb_usuario_adm tb_usuario_adm { get; set; }
    }
}
