//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_log_usuario_alteracao
    {
        public long cd_log_usuario_alteracao { get; set; }
        public long cd_usuario { get; set; }
        public string ds_alteracao { get; set; }
        public System.DateTime dt_log_alteracao { get; set; }
        public int cd_usuario_adm { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
        public virtual tb_usuario_adm tb_usuario_adm { get; set; }
    }
}
