//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_log_email
    {
        public long cd_log_email { get; set; }
        public Nullable<long> cd_usuario { get; set; }
        public string ds_mensagem { get; set; }
        public string ds_email_usuario { get; set; }
        public string nu_codigo_email { get; set; }
        public System.DateTime dt_envio { get; set; }
        public string nu_chave_guid { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
