//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_log_localizacao_usuario
    {
        public long cd_log_localizacao_usuario { get; set; }
        public Nullable<long> cd_usuario { get; set; }
        public Nullable<System.DateTime> dt_log { get; set; }
        public string nu_latitude { get; set; }
        public string nu_longitude { get; set; }
    }
}
