//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_log_pedido_estocagem
    {
        public int cd_log_pedido_estocagem { get; set; }
        public Nullable<long> cd_pedido { get; set; }
        public Nullable<long> cd_pedido_item { get; set; }
        public Nullable<int> cd_operadora { get; set; }
        public Nullable<System.DateTime> dt_log { get; set; }
        public Nullable<int> tp_tipo_log { get; set; }
    }
}
