//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_log_notificacao_gateway
    {
        public long cd_log_notificacao_gateway { get; set; }
        public string ds_log_notificacao_gateway { get; set; }
        public System.DateTime dt_log_notificacao_gateway { get; set; }
        public Nullable<System.DateTime> dt_log_analise { get; set; }
        public Nullable<bool> ic_error_autorization_front_end { get; set; }
        public Nullable<long> cd_pedido { get; set; }
    }
}
