//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_menu_adm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_menu_adm()
        {
            this.tb_sub_menu_adm = new HashSet<tb_sub_menu_adm>();
        }
    
        public int cd_menu_adm { get; set; }
        public string ds_menu_adm { get; set; }
        public Nullable<short> nu_ordem_visualicao { get; set; }
        public string ds_icone_menu_adm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_sub_menu_adm> tb_sub_menu_adm { get; set; }
    }
}
