//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_natureza_juridica
    {
        public int cd_natureza_juridica { get; set; }
        public string ds_cod_banco_natureza_juridica { get; set; }
        public string nm_natureza_juridica { get; set; }
        public string ds_documento_natureza_juridica { get; set; }
        public string tp_categoria { get; set; }
        public Nullable<bool> ic_documento_obrigatorio { get; set; }
    }
}
