//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_operadora_parceiro_logistico
    {
        public int cd_operadora_parceiro_logistico { get; set; }
        public int cd_parceiro_logistico { get; set; }
        public int cd_operadora { get; set; }
        public bool ic_operadora_parceiro_logistico_inativo { get; set; }
        public decimal vl_frete_parceiro_logistico { get; set; }
    
        public virtual tb_operadora tb_operadora { get; set; }
        public virtual tb_parceiro_logistico tb_parceiro_logistico { get; set; }
    }
}
