//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_operadora_mensagem
    {
        public int cd_operadora_mensagem { get; set; }
        public int cd_operadora { get; set; }
        public short tp_pedido_item { get; set; }
        public string ds_mensagem { get; set; }
        public bool ic_inativo { get; set; }
        public string ds_mensagem_reduzida { get; set; }
        public string ds_link_imagem_mensagem { get; set; }
    
        public virtual tb_operadora tb_operadora { get; set; }
    }
}
