//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_operadora_acerto
    {
        public long cd_pedido_item { get; set; }
        public Nullable<System.DateTime> dt_registro_operadora_acerto { get; set; }
        public Nullable<decimal> vl_valor_recarga { get; set; }
        public Nullable<decimal> vl_taxa { get; set; }
        public Nullable<decimal> vl_desconto { get; set; }
        public Nullable<decimal> vl_total_pedido { get; set; }
        public Nullable<decimal> vl_valor_pago { get; set; }
        public Nullable<System.DateTime> dt_datahora_pedido_operadora { get; set; }
        public Nullable<int> nu_dias_repasse { get; set; }
        public Nullable<System.DateTime> dt_repasse { get; set; }
        public Nullable<System.DateTime> dt_faturamento { get; set; }
        public Nullable<decimal> vl_percentual_faturamento { get; set; }
        public Nullable<decimal> vl_comissao { get; set; }
    
        public virtual tb_pedido_item tb_pedido_item { get; set; }
    }
}
