//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ofertas
    {
        public long cd_oferta { get; set; }
        public string cd_cod_oferta { get; set; }
        public string ds_oferta { get; set; }
        public long cd_ofertas_categoria { get; set; }
        public string lnk_oferta { get; set; }
        public string ds_thumbnail_oferta { get; set; }
        public Nullable<decimal> vl_oferta { get; set; }
        public Nullable<decimal> vl_oferta_origem { get; set; }
        public long cd_ofertas_loja { get; set; }
        public bool ic_top_ofertas { get; set; }
        public Nullable<bool> ic_exibir_ofertas { get; set; }
    
        public virtual tb_ofertas_categoria tb_ofertas_categoria { get; set; }
        public virtual tb_ofertas_loja tb_ofertas_loja { get; set; }
    }
}
