//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_operadora_cidade
    {
        public int cd_operadora_cidade { get; set; }
        public int cd_operadora { get; set; }
        public int cd_cidade { get; set; }
        public short nu_ordem_visualizacao { get; set; }
    
        public virtual tb_cidade tb_cidade { get; set; }
        public virtual tb_operadora tb_operadora { get; set; }
    }
}
