//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_operadora_revenda_secundaria
    {
        public int cd_operadora_revenda_secundaria { get; set; }
        public Nullable<int> cd_operadora { get; set; }
        public Nullable<int> nu_codigo_revenda_operadora { get; set; }
        public string ds_usuario_auth { get; set; }
        public string ds_senha_auth { get; set; }
        public string ds_token_CitSoa { get; set; }
    
        public virtual tb_operadora tb_operadora { get; set; }
    }
}
