//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_operadora_empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_operadora_empresa()
        {
            this.tb_operadora_empresa_tipo_cartao = new HashSet<tb_operadora_empresa_tipo_cartao>();
            this.tb_terminal = new HashSet<tb_terminal>();
            this.tb_usuario_adm_operadora_empresa = new HashSet<tb_usuario_adm_operadora_empresa>();
        }
    
        public int cd_operadora_empresa { get; set; }
        public int cd_operadora { get; set; }
        public string nm_operadora_empresa { get; set; }
        public bool ic_inativo { get; set; }
        public int cd_cod_operadora_sbe { get; set; }
    
        public virtual tb_operadora tb_operadora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_operadora_empresa_tipo_cartao> tb_operadora_empresa_tipo_cartao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_terminal> tb_terminal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuario_adm_operadora_empresa> tb_usuario_adm_operadora_empresa { get; set; }
    }
}
