//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_operadora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_operadora()
        {
            this.tb_faq = new HashSet<tb_faq>();
            this.tb_tipo_cartao = new HashSet<tb_tipo_cartao>();
            this.tb_operadora_banco_conta = new HashSet<tb_operadora_banco_conta>();
            this.tb_operadora_cidade = new HashSet<tb_operadora_cidade>();
            this.tb_operadora_empresa = new HashSet<tb_operadora_empresa>();
            this.tb_operadora_forma_pagamento_gateway = new HashSet<tb_operadora_forma_pagamento_gateway>();
            this.tb_operadora_linha = new HashSet<tb_operadora_linha>();
            this.tb_operadora_mapa_params = new HashSet<tb_operadora_mapa_params>();
            this.tb_operadora_mensagem = new HashSet<tb_operadora_mensagem>();
            this.tb_operadora_parceiro_logistico = new HashSet<tb_operadora_parceiro_logistico>();
            this.tb_operadora_revenda_secundaria = new HashSet<tb_operadora_revenda_secundaria>();
            this.tb_operadora_tipo_canal = new HashSet<tb_operadora_tipo_canal>();
            this.tb_parametro_comissao = new HashSet<tb_parametro_comissao>();
            this.tb_pedido_revenda = new HashSet<tb_pedido_revenda>();
            this.tb_posto_operadora = new HashSet<tb_posto_operadora>();
            this.tb_taxa_adm = new HashSet<tb_taxa_adm>();
            this.tb_taxa_operadora_tipo_cartao = new HashSet<tb_taxa_operadora_tipo_cartao>();
            this.tb_terminal = new HashSet<tb_terminal>();
            this.tb_usuario_favorito_linha = new HashSet<tb_usuario_favorito_linha>();
            this.tb_usuario_favorito_paradas = new HashSet<tb_usuario_favorito_paradas>();
            this.tb_usuario_revenda_operadora = new HashSet<tb_usuario_revenda_operadora>();
        }
    
        public int cd_operadora { get; set; }
        public string nu_cnpj_operadora { get; set; }
        public string nm_razao_social_operadora { get; set; }
        public string nm_fantasia_operadora { get; set; }
        public bool ic_operadora_inativo { get; set; }
        public string nm_sigla_operadora { get; set; }
        public Nullable<int> nu_codigo_revenda_operadora { get; set; }
        public string ds_servidor_conexao { get; set; }
        public string ds_servidor_autorizacao { get; set; }
        public string ds_caminho_logo { get; set; }
        public string ds_usuario_auth { get; set; }
        public string ds_senha_auth { get; set; }
        public string ds_url_taxa { get; set; }
        public Nullable<bool> ic_monitoramento_terminal { get; set; }
        public Nullable<int> cd_operadora_versao_api { get; set; }
        public string ds_token_operadora { get; set; }
        public string ds_token_CitSoa { get; set; }
        public Nullable<bool> ic_cartao_virtual { get; set; }
        public bool ic_recarga_cartao_transporte { get; set; }
        public bool ic_recarga_celular { get; set; }
        public bool ic_recarga_servicos_digitais { get; set; }
        public bool ic_clube_beneficios { get; set; }
        public bool ic_recarga_tv_prepaga { get; set; }
        public bool ic_valor_editavel { get; set; }
        public bool ic_valida_cartao_antigo { get; set; }
        public Nullable<bool> ic_desconto_comissao { get; set; }
        public Nullable<bool> ic_mapa { get; set; }
        public string ds_servidor_mapa { get; set; }
        public string ds_versao { get; set; }
        public string ds_url_conveniencia { get; set; }
        public bool ic_revenda { get; set; }
        public bool ic_revenda_especial { get; set; }
        public Nullable<bool> ic_doacao { get; set; }
        public Nullable<bool> ic_repasse_taxa { get; set; }
        public Nullable<bool> ic_exibir_extrato { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_faq> tb_faq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_tipo_cartao> tb_tipo_cartao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_operadora_banco_conta> tb_operadora_banco_conta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_operadora_cidade> tb_operadora_cidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_operadora_empresa> tb_operadora_empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_operadora_forma_pagamento_gateway> tb_operadora_forma_pagamento_gateway { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_operadora_linha> tb_operadora_linha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_operadora_mapa_params> tb_operadora_mapa_params { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_operadora_mensagem> tb_operadora_mensagem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_operadora_parceiro_logistico> tb_operadora_parceiro_logistico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_operadora_revenda_secundaria> tb_operadora_revenda_secundaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_operadora_tipo_canal> tb_operadora_tipo_canal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_parametro_comissao> tb_parametro_comissao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_revenda> tb_pedido_revenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_posto_operadora> tb_posto_operadora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_taxa_adm> tb_taxa_adm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_taxa_operadora_tipo_cartao> tb_taxa_operadora_tipo_cartao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_terminal> tb_terminal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuario_favorito_linha> tb_usuario_favorito_linha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuario_favorito_paradas> tb_usuario_favorito_paradas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuario_revenda_operadora> tb_usuario_revenda_operadora { get; set; }
    }
}
