//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_operadora_forma_pagamento_gateway
    {
        public int cd_operadora_forma_pagamento_gateway { get; set; }
        public int cd_operadora { get; set; }
        public short cd_forma_pagamento { get; set; }
        public short cd_gateway { get; set; }
        public bool ic_processamento_operadora { get; set; }
        public bool ic_processamento_inativo { get; set; }
        public short ic_ordem_execucao { get; set; }
    
        public virtual tb_forma_pagamento tb_forma_pagamento { get; set; }
        public virtual tb_gateway tb_gateway { get; set; }
        public virtual tb_operadora tb_operadora { get; set; }
    }
}
