//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_operadora_linha
    {
        public long cd_operadora_linha { get; set; }
        public int cd_operadora { get; set; }
        public string id_linha_sbe { get; set; }
        public string id_cod_ext_linha_sbe { get; set; }
        public string nm_linha_sbe { get; set; }
        public string ds_tipo_linha { get; set; }
        public string ds_tarifa_cliente_linha { get; set; }
        public Nullable<decimal> vl_tarifa_linha { get; set; }
        public string ds_linha_geral { get; set; }
        public string ds_tag_linha { get; set; }
        public Nullable<bool> ic_estacao { get; set; }
        public Nullable<System.DateTime> dt_atualizacao { get; set; }
        public Nullable<bool> ic_possui_qrcode { get; set; }
    
        public virtual tb_operadora tb_operadora { get; set; }
    }
}
