//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_operadora_empresa_tipo_cartao
    {
        public int cd_operadora_empresa_tipo_cartao { get; set; }
        public Nullable<int> cd_operadora_empresa { get; set; }
        public Nullable<int> cd_tipo_cartao { get; set; }
    
        public virtual tb_operadora_empresa tb_operadora_empresa { get; set; }
        public virtual tb_tipo_cartao tb_tipo_cartao { get; set; }
    }
}
