//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_operadora_mapa_params
    {
        public int cd_operadora_mapa_params { get; set; }
        public Nullable<int> cd_operadora { get; set; }
        public string ds_titulo { get; set; }
        public Nullable<bool> ic_funcionalidade { get; set; }
        public Nullable<bool> ic_pagina { get; set; }
        public Nullable<bool> ic_ativo { get; set; }
        public string ds_titulo_exibicao { get; set; }
    
        public virtual tb_operadora tb_operadora { get; set; }
    }
}
