//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_paradas
    {
        public int cd_parada { get; set; }
        public string id_parada { get; set; }
        public string ds_parada { get; set; }
        public string cd_siu_parada { get; set; }
        public string nu_latitude { get; set; }
        public string nu_longitude { get; set; }
        public Nullable<int> cd_operadora { get; set; }
        public Nullable<System.DateTime> dt_atualizacao { get; set; }
    }
}
