//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_parametro_rv
    {
        public int cd_parametro_rv { get; set; }
        public string ds_url_autorizacao { get; set; }
        public string ds_client_id { get; set; }
        public string ds_client_secret { get; set; }
        public string ds_token { get; set; }
        public Nullable<System.DateTime> dt_validade_token { get; set; }
        public string ds_url { get; set; }
    }
}
