//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_parametro_comissao
    {
        public int cd_parametro_comissao_revemda { get; set; }
        public int cd_operadora { get; set; }
        public decimal vl_aliq_comissao { get; set; }
        public System.DateTime dt_inicio_comissao { get; set; }
        public System.DateTime dt_fim_comissao { get; set; }
    
        public virtual tb_operadora tb_operadora { get; set; }
    }
}
