//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pagamento_pedido_parcelado
    {
        public long cd_pagamento_pedido_parcelado { get; set; }
        public Nullable<long> cd_pedido { get; set; }
        public Nullable<short> cd_gateway { get; set; }
        public Nullable<int> nu_qtd_parcelas { get; set; }
        public Nullable<decimal> vl_parcela { get; set; }
        public Nullable<decimal> vl_taxa_mes { get; set; }
        public Nullable<decimal> vl_total_com_taxa { get; set; }
        public Nullable<decimal> vl_total_sem_taxa { get; set; }
    }
}
