//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido_revenda
    {
        public long cd_pedido { get; set; }
        public long cd_usuario { get; set; }
        public int cd_operadora { get; set; }
        public decimal vl_total_pedido { get; set; }
        public System.DateTime dt_pedido { get; set; }
        public decimal vl_total_liquido { get; set; }
        public bool ic_processado { get; set; }
        public Nullable<System.DateTime> dt_processamento { get; set; }
        public string ds_chave_processamento { get; set; }
        public decimal vl_total_liquido_operadora { get; set; }
        public bool ic_processado_comissao { get; set; }
        public Nullable<System.DateTime> dt_processamento_comissao { get; set; }
        public string ds_chave_processamento_comissao { get; set; }
    
        public virtual tb_operadora tb_operadora { get; set; }
        public virtual tb_pedido tb_pedido { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
