//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido_entrega
    {
        public int cd_pedido_entrega { get; set; }
        public long cd_pedido { get; set; }
        public string ds_tipo_logradouro_entrega { get; set; }
        public int nu_logradouro_entrega { get; set; }
        public string ds_complemento_logradouro_entrega { get; set; }
        public string nm_bairro_entrega { get; set; }
        public string nm_municipio_entrega { get; set; }
        public string nm_logradouro_entrega { get; set; }
        public short cd_uf { get; set; }
        public string nu_cep_entrega { get; set; }
        public string ds_codigo_ibge_entrega { get; set; }
    
        public virtual tb_pedido tb_pedido { get; set; }
        public virtual tb_uf tb_uf { get; set; }
    }
}
