//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pagina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_pagina()
        {
            this.tb_pagina_controle = new HashSet<tb_pagina_controle>();
        }
    
        public int cd_pagina { get; set; }
        public string ds_descricao_pagina { get; set; }
        public Nullable<int> cd_banner { get; set; }
        public string ds_titulo_pagina { get; set; }
        public string ds_cor_titulo { get; set; }
        public string ds_cor_fundo_banner { get; set; }
        public string ds_link_logo { get; set; }
        public string ds_cor_fundo_pagina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pagina_controle> tb_pagina_controle { get; set; }
    }
}
