//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_parametro_email
    {
        public int cd_parametro_email { get; set; }
        public string ds_from { get; set; }
        public string ds_usuario { get; set; }
        public string ds_senha { get; set; }
        public string ds_host { get; set; }
        public int nu_porta { get; set; }
        public bool ic_EMPRESA3mais { get; set; }
        public bool ic_EMPRESA3mais_revenda { get; set; }
    }
}
