//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_pedido_item()
        {
            this.tb_estorno_pedido_item = new HashSet<tb_estorno_pedido_item>();
            this.tb_log_pedido_item = new HashSet<tb_log_pedido_item>();
            this.tb_log_pedido_item_cancelamento_rv = new HashSet<tb_log_pedido_item_cancelamento_rv>();
            this.tb_pedido_item_cartao = new HashSet<tb_pedido_item_cartao>();
        }
    
        public long cd_pedido_item { get; set; }
        public long cd_pedido { get; set; }
        public Nullable<long> cd_usuario_cartao { get; set; }
        public decimal vl_valor_recarga { get; set; }
        public Nullable<decimal> vl_taxa { get; set; }
        public Nullable<decimal> vl_desconto { get; set; }
        public Nullable<short> cd_status_pedido_item { get; set; }
        public string ds_pedido_operadora { get; set; }
        public Nullable<System.DateTime> dt_datahora_pedido_operadora { get; set; }
        public short tp_pedido_item { get; set; }
        public Nullable<int> cd_tipo_cartao { get; set; }
        public bool ic_credito_confianca { get; set; }
        public Nullable<bool> ic_processado_fidelidade { get; set; }
        public string nu_ddd_recarga_celular { get; set; }
        public string nu_tel_recarga_celular { get; set; }
        public Nullable<int> cd_tipo_cartao_valor { get; set; }
        public string ds_retorno_arquivo { get; set; }
        public string nu_cpf_cod_assinatura { get; set; }
        public Nullable<decimal> vl_cashback { get; set; }
        public Nullable<bool> ic_pre_pedido_operadora { get; set; }
        public string ds_num_pre_pedido_operadora { get; set; }
        public Nullable<System.DateTime> dt_pre_pedido_operadora { get; set; }
        public string ds_cod_compra_operadora { get; set; }
        public decimal vl_comissao { get; set; }
        public Nullable<decimal> vl_entrega { get; set; }
        public Nullable<int> cd_operadora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_estorno_pedido_item> tb_estorno_pedido_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_log_pedido_item> tb_log_pedido_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_log_pedido_item_cancelamento_rv> tb_log_pedido_item_cancelamento_rv { get; set; }
        public virtual tb_operadora_acerto tb_operadora_acerto { get; set; }
        public virtual tb_pedido tb_pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_item_cartao> tb_pedido_item_cartao { get; set; }
        public virtual tb_status_pedido_item tb_status_pedido_item { get; set; }
        public virtual tb_tipo_cartao tb_tipo_cartao { get; set; }
        public virtual tb_tipo_cartao_valor tb_tipo_cartao_valor { get; set; }
    }
}
