//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_posto_operadora
    {
        public int cd_posto_operadora { get; set; }
        public int cd_posto { get; set; }
        public int cd_operadora { get; set; }
        public bool ic_posto_operadora_inativo { get; set; }
    
        public virtual tb_operadora tb_operadora { get; set; }
        public virtual tb_posto tb_posto { get; set; }
    }
}
