//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_pedido()
        {
            this.tb_avaliacao = new HashSet<tb_avaliacao>();
            this.tb_boleto = new HashSet<tb_boleto>();
            this.tb_estorno_pedido = new HashSet<tb_estorno_pedido>();
            this.tb_fila_analise_revalidacao = new HashSet<tb_fila_analise_revalidacao>();
            this.tb_ged_pedido = new HashSet<tb_ged_pedido>();
            this.tb_ged_pedido_cartao = new HashSet<tb_ged_pedido_cartao>();
            this.tb_ged_revalidacao = new HashSet<tb_ged_revalidacao>();
            this.tb_pedido_entrega = new HashSet<tb_pedido_entrega>();
            this.tb_pedido_item = new HashSet<tb_pedido_item>();
            this.tb_pedido_pagamento_picpay = new HashSet<tb_pedido_pagamento_picpay>();
            this.tb_pedido_pagamento_pix = new HashSet<tb_pedido_pagamento_pix>();
            this.tb_rel_liq_cobranca = new HashSet<tb_rel_liq_cobranca>();
            this.tb_tarefa_entrega = new HashSet<tb_tarefa_entrega>();
        }
    
        public long cd_pedido { get; set; }
        public long cd_usuario { get; set; }
        public System.DateTime dt_datahora_pedido { get; set; }
        public short cd_forma_pagamento { get; set; }
        public short cd_status_pedido { get; set; }
        public decimal vl_pedido { get; set; }
        public decimal vl_taxa { get; set; }
        public Nullable<decimal> vl_desconto { get; set; }
        public decimal vl_total_pedido { get; set; }
        public Nullable<System.DateTime> dt_data_pagamento { get; set; }
        public Nullable<decimal> vl_valor_pago { get; set; }
        public string ds_chave_transacao { get; set; }
        public Nullable<short> cd_motivo_baixa_manual { get; set; }
        public Nullable<System.DateTime> dt_baixa_manual { get; set; }
        public Nullable<int> cd_usuario_adm_baixa_manual { get; set; }
        public Nullable<bool> ic_export_erp { get; set; }
        public Nullable<System.DateTime> dt_export_erp { get; set; }
        public Nullable<short> cd_canal { get; set; }
        public Nullable<long> cd_usuario_cupom { get; set; }
        public bool ic_transacao_analise_risco { get; set; }
        public Nullable<long> cd_usuario_cupom_programa_fidelidade { get; set; }
        public Nullable<bool> ic_repetir_pedido { get; set; }
        public Nullable<decimal> vl_cashback { get; set; }
        public Nullable<bool> ic_cashback_processado { get; set; }
        public Nullable<System.DateTime> dt_cashback_processado { get; set; }
        public bool ic_revenda { get; set; }
        public decimal vl_comissao { get; set; }
        public Nullable<bool> ic_pagamento_lote { get; set; }
        public Nullable<System.DateTime> dt_pagamento_lote { get; set; }
        public string ds_num_pagamento_lote { get; set; }
        public Nullable<decimal> vl_taxa_transacao_lote { get; set; }
        public Nullable<decimal> vl_liquido_transacao_lote { get; set; }
        public Nullable<short> cd_gateway { get; set; }
        public Nullable<decimal> vl_total_entrega { get; set; }
        public string ds_ip_usuario { get; set; }
        public Nullable<bool> ic_pagamento_parcelado { get; set; }
        public Nullable<decimal> vl_acrescimo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_avaliacao> tb_avaliacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_boleto> tb_boleto { get; set; }
        public virtual tb_canal tb_canal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_estorno_pedido> tb_estorno_pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_fila_analise_revalidacao> tb_fila_analise_revalidacao { get; set; }
        public virtual tb_forma_pagamento tb_forma_pagamento { get; set; }
        public virtual tb_gateway tb_gateway { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ged_pedido> tb_ged_pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ged_pedido_cartao> tb_ged_pedido_cartao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ged_revalidacao> tb_ged_revalidacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_entrega> tb_pedido_entrega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_item> tb_pedido_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_pagamento_picpay> tb_pedido_pagamento_picpay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_pagamento_pix> tb_pedido_pagamento_pix { get; set; }
        public virtual tb_pedido_revenda tb_pedido_revenda { get; set; }
        public virtual tb_status_pedido tb_status_pedido { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
        public virtual tb_usuario_cupom tb_usuario_cupom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_rel_liq_cobranca> tb_rel_liq_cobranca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_tarefa_entrega> tb_tarefa_entrega { get; set; }
    }
}
