//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_parametro_tentativa_most
    {
        public int cd_parametro_tentativa_most { get; set; }
        public Nullable<int> qtd_intervalo_dias { get; set; }
        public Nullable<int> qtd_tentativas_operadora { get; set; }
        public Nullable<int> qtd_tentativas_EMPRESA3 { get; set; }
    }
}
