//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_parametro_cashdeal
    {
        public int cd_parametros_cashdeal { get; set; }
        public string ds_url_cashdeal { get; set; }
        public string ds_access_token { get; set; }
        public string ds_refresh_token { get; set; }
        public Nullable<System.DateTime> dt_validade_token { get; set; }
        public string ds_client_id { get; set; }
        public string ds_permanent_code { get; set; }
    }
}
