//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_parametro_pix_wso
    {
        public int cd_parametro_pix_wso { get; set; }
        public string ds_flow_id { get; set; }
        public string ds_tenant_id { get; set; }
        public bool ic_inativo { get; set; }
        public string ds_senha { get; set; }
        public string ds_usuariopix { get; set; }
        public string ds_token { get; set; }
        public Nullable<System.DateTime> dt_validade_token { get; set; }
    }
}
