//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_parceiro_logistico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_parceiro_logistico()
        {
            this.tb_operadora_parceiro_logistico = new HashSet<tb_operadora_parceiro_logistico>();
        }
    
        public int cd_parceiro_logistico { get; set; }
        public string ds_parceiro_logistico { get; set; }
        public string nu_parceiro_logistico_ddd_telefone { get; set; }
        public string nu_parceiro_logistico_telefone { get; set; }
        public string ds_parceiro_logistico_tipo_logradouro { get; set; }
        public string nm_parceiro_logistico_logradouro { get; set; }
        public int nu_parceiro_logistico_logradouro { get; set; }
        public string ds_parceiro_logistico_complemento_logradouro { get; set; }
        public string nm_parceiro_logistico_bairro { get; set; }
        public string nm_parceiro_logistico_municipio { get; set; }
        public short cd_uf { get; set; }
        public string nu_parceiro_logistico_cep { get; set; }
        public bool ic_parceiro_logistico_inativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_operadora_parceiro_logistico> tb_operadora_parceiro_logistico { get; set; }
    }
}
