//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_programa_fidelidade_resgate
    {
        public short cd_programa_fidelidade_resgate { get; set; }
        public string ds_programa_fidelidade_resgate { get; set; }
        public int nu_pontos { get; set; }
        public decimal vl_carga { get; set; }
        public bool ic_inativo { get; set; }
    }
}
