//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_parametro_anti_fraude
    {
        public short cd_parametro_anti_fraude { get; set; }
        public short nu_qtd_dia_recarga_celular { get; set; }
        public short nu_qtd_semana_recarga_celular { get; set; }
        public short nu_qtd_dia_recarga_servico_digital { get; set; }
        public short nu_qtd_semana_recarga_servico_digital { get; set; }
        public short nu_qtd_alterar_num_celular { get; set; }
        public short nu_qtd_dia_recarga_tv { get; set; }
        public short nu_qtd_semana_recarga_tv { get; set; }
    }
}
