//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_parameto_itau
    {
        public short cd_parameto_itau { get; set; }
        public string ds_codigo_moeda_cnab { get; set; }
        public int int_tipo_juros { get; set; }
        public int int_tipo_multa { get; set; }
        public int int_tipo_desconto { get; set; }
        public string ds_tipo_autorizacao_recebimento { get; set; }
        public int int_tipo_ambiente { get; set; }
        public int int_tipo_registro { get; set; }
        public int int_tipo_cobranca { get; set; }
        public string ds_tipo_produto { get; set; }
        public string ds_tipo_sub_produto { get; set; }
        public string ds_titulo_aceite { get; set; }
        public string ds_tipo_especie { get; set; }
        public int int_tipo_pagamento { get; set; }
        public bool ic_indicador_pagamento_parcial { get; set; }
    }
}
