//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido_item_cartao
    {
        public long cd_pedido_item_cartao { get; set; }
        public long cd_pedido_item { get; set; }
        public int cd_posto { get; set; }
        public bool ic_retirada_entrega { get; set; }
        public System.DateTime dt_registro { get; set; }
        public short cd_status_pedido_item_cartao { get; set; }
        public Nullable<bool> ic_finalizado_operadora { get; set; }
        public Nullable<System.DateTime> dt_finalizado_operadora { get; set; }
        public Nullable<int> cd_usuario_adm { get; set; }
        public string ds_tipo_logradouro_entrega { get; set; }
        public string nm_logradouro_entrega { get; set; }
        public Nullable<int> nu_logradouro_entrega { get; set; }
        public string ds_complemento_logradouro_entrega { get; set; }
        public string nm_bairro_entrega { get; set; }
        public string nm_municipio_entrega { get; set; }
        public Nullable<short> cd_uf { get; set; }
        public string nu_cep_entrega { get; set; }
        public string cod_pedido_operadora { get; set; }
        public string cod_pacote_operadora { get; set; }
        public Nullable<System.DateTime> dt_envio_pedido_operadora { get; set; }
        public string ds_retorno_operadora { get; set; }
        public Nullable<int> cd_usuario_adm_entrega { get; set; }
        public byte[] img_documento_entrega { get; set; }
    
        public virtual tb_pedido_item tb_pedido_item { get; set; }
        public virtual tb_posto tb_posto { get; set; }
        public virtual tb_uf tb_uf { get; set; }
        public virtual tb_usuario_adm tb_usuario_adm { get; set; }
        public virtual tb_usuario_adm tb_usuario_adm1 { get; set; }
    }
}
