//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pagina_cupom
    {
        public int cd_pagina_cupom { get; set; }
        public Nullable<int> cd_banner { get; set; }
        public string ds_titulo_pagina { get; set; }
        public string ds_subtitulo_pagina { get; set; }
        public string ds_texto_pre_cupons { get; set; }
        public string ds_titulo_cupom1 { get; set; }
        public string ds_texto_cupom1 { get; set; }
        public string ds_titulo_cupom2 { get; set; }
        public string ds_texto_cupom2 { get; set; }
        public string ds_titulo_cupom3 { get; set; }
        public string ds_texto_cupom3 { get; set; }
        public string ds_titulo_cupom4 { get; set; }
        public string ds_texto_cupom4 { get; set; }
        public string ds_titulo_cupom5 { get; set; }
        public string ds_texto_cupom5 { get; set; }
        public string ds_texto_botao { get; set; }
        public string ds_link_botao { get; set; }
        public string ds_texto_abaixo_botao { get; set; }
        public string ds_titulo_regras { get; set; }
        public string ds_subtitulo_regra1 { get; set; }
        public string ds_texto_regra1 { get; set; }
        public string ds_subtitulo_regra2 { get; set; }
        public string ds_texto_regra2 { get; set; }
        public string ds_subtitulo_regra3 { get; set; }
        public string ds_texto_regra3 { get; set; }
        public string ds_subtitulo_regra4 { get; set; }
        public string ds_texto_regra4 { get; set; }
        public string ds_subtitulo_regra5 { get; set; }
        public string ds_texto_regra5 { get; set; }
        public string ds_cor_titulo { get; set; }
        public string ds_cor_fundo_banner { get; set; }
        public string ds_link_logo { get; set; }
        public string ds_cor_fundo_pagina { get; set; }
        public string ds_cor_texto_pagina { get; set; }
        public string ds_cor_texto_cupom { get; set; }
        public string ds_cor_botao { get; set; }
        public string ds_cor_texto_botao { get; set; }
        public Nullable<bool> ic_ativo { get; set; }
    
        public virtual tb_banner tb_banner { get; set; }
    }
}
