//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido_atm
    {
        public long cd_pedido_atm { get; set; }
        public long cd_usuario { get; set; }
        public string cd_idtx { get; set; }
        public string ds_atm { get; set; }
        public string nu_cartao_interno { get; set; }
        public string nu_cartao_fisico { get; set; }
        public short ic_status_pedido { get; set; }
        public decimal vl_pedido { get; set; }
        public decimal vl_comissao { get; set; }
        public decimal vl_liquido { get; set; }
        public System.DateTime dt_pedido { get; set; }
        public string ds_text_pixcode { get; set; }
        public string ds_img_pixcode { get; set; }
        public string ds_url_pixcode { get; set; }
        public System.DateTime dt_validade_pix { get; set; }
        public bool ic_pagamento { get; set; }
        public Nullable<System.DateTime> dt_pagamento { get; set; }
        public string ds_chave_processamento_operadora { get; set; }
        public Nullable<System.DateTime> dt_processamento_operadora { get; set; }
        public bool ic_processado_operadora { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
