//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido_pagamento_pix
    {
        public long cd_pedido_pagamento_pix { get; set; }
        public long cd_pedido { get; set; }
        public System.DateTime dt_geracao_cobranca { get; set; }
        public short cd_status_pedido_pagamento_pix { get; set; }
        public string ds_flowid_wso { get; set; }
        public string ds_tenant_id_wso { get; set; }
        public string nu_pix_idtx { get; set; }
        public string ds_pix_imagem { get; set; }
        public string ds_pix_link { get; set; }
        public string ds_pix_emv { get; set; }
        public Nullable<System.DateTime> dt_pix_validade { get; set; }
        public decimal vl_pedido_pagamento_pix { get; set; }
        public Nullable<System.DateTime> dt_pedido_pagamento_pix { get; set; }
        public Nullable<decimal> vl_pago_pedido_pagamento_pix { get; set; }
        public string nu_id_endtoend { get; set; }
        public string ds_id_order_cashdeal { get; set; }
        public string ds_id_charge_cashdeal { get; set; }
        public Nullable<System.DateTime> dt_notificacao_pagamento { get; set; }
        public Nullable<short> cd_gateway { get; set; }
    
        public virtual tb_pedido tb_pedido { get; set; }
        public virtual tb_status_pedido_pagamento_pix tb_status_pedido_pagamento_pix { get; set; }
    }
}
