//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_recarga_automatica
    {
        public long cd_recarga_automatica { get; set; }
        public long cd_usuario { get; set; }
        public long cd_usuario_cartao { get; set; }
        public decimal vl_saldo_recarga { get; set; }
        public decimal vl_recarga_automatica { get; set; }
        public Nullable<System.DateTime> dt_ultima_execucao { get; set; }
        public long cd_usuario_cartao_credito { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
        public virtual tb_usuario_cartao tb_usuario_cartao { get; set; }
        public virtual tb_usuario_cartao_credito tb_usuario_cartao_credito { get; set; }
    }
}
