//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_requisicao_qrcode
    {
        public int cd_requisicao_qrcode { get; set; }
        public string ds_requisicao { get; set; }
        public string ds_retorno { get; set; }
        public Nullable<System.DateTime> dt_operacao { get; set; }
        public Nullable<long> cd_usuario { get; set; }
        public Nullable<System.DateTime> dt_retorno { get; set; }
        public Nullable<long> cd_usuario_cartao { get; set; }
    }
}
