//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_requisicao_via
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_requisicao_via()
        {
            this.tb_historico_requisicao_via = new HashSet<tb_historico_requisicao_via>();
        }
    
        public long cd_requisicao_via { get; set; }
        public Nullable<long> cd_usuario { get; set; }
        public string nu_codigo_usuario_operadora { get; set; }
        public Nullable<int> cd_operadora { get; set; }
        public string ds_nome_estudante { get; set; }
        public Nullable<System.DateTime> dt_nascimento { get; set; }
        public string ds_nome_mae { get; set; }
        public string nu_rg { get; set; }
        public string nu_cpf { get; set; }
        public Nullable<int> tp_requisicao { get; set; }
        public Nullable<System.DateTime> dt_requisicao { get; set; }
        public Nullable<int> cd_status_requisicao { get; set; }
        public Nullable<long> cd_pedido { get; set; }
        public Nullable<int> cd_tipo_cartao { get; set; }
        public string ds_nome_pai { get; set; }
        public string ds_genero { get; set; }
        public string ds_email { get; set; }
        public string nu_ddd { get; set; }
        public string nu_tel { get; set; }
        public string nu_cep { get; set; }
        public string ds_logradouro { get; set; }
        public string nu_numero { get; set; }
        public string ds_complemento { get; set; }
        public string ds_bairro { get; set; }
        public string ds_municipio { get; set; }
        public string sg_UF { get; set; }
        public Nullable<int> cd_etapa_via { get; set; }
        public Nullable<int> cd_usuario_adm { get; set; }
        public Nullable<long> cd_usuario_cartao { get; set; }
        public Nullable<System.DateTime> dt_onboard_dependente { get; set; }
        public string cd_dependente_sbe { get; set; }
        public Nullable<System.DateTime> dt_aceite_termo { get; set; }
        public Nullable<bool> ic_estudante_vinculado_sbe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_historico_requisicao_via> tb_historico_requisicao_via { get; set; }
    }
}
