//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_status_pedido_pagamento_pix
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_status_pedido_pagamento_pix()
        {
            this.tb_pedido_pagamento_pix = new HashSet<tb_pedido_pagamento_pix>();
        }
    
        public short cd_status_pedido_pagamento_pix { get; set; }
        public string ds_status { get; set; }
        public bool ic_inativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_pagamento_pix> tb_pedido_pagamento_pix { get; set; }
    }
}
