//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sub_menu_adm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_sub_menu_adm()
        {
            this.tb_perfil_sub_menu_adm = new HashSet<tb_perfil_sub_menu_adm>();
        }
    
        public int cd_sub_menu_adm { get; set; }
        public int cd_menu_adm { get; set; }
        public string ds_sub_menu_adm { get; set; }
        public string ds_url_sub_menu_adm { get; set; }
        public Nullable<bool> ic_sub_menu_adm_inativo { get; set; }
        public Nullable<short> nu_sub_menu_adm_ordem { get; set; }
    
        public virtual tb_menu_adm tb_menu_adm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_perfil_sub_menu_adm> tb_perfil_sub_menu_adm { get; set; }
    }
}
