//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_servico
    {
        public short cd_servico { get; set; }
        public string ds_nome_servico { get; set; }
        public Nullable<System.DateTime> dt_ultima_exec_saldo { get; set; }
        public bool ic_servico_inativo { get; set; }
        public string ds_servico_link_push { get; set; }
        public string ds_servico_token_push { get; set; }
        public Nullable<System.DateTime> dt_proxima_exec_saldo_mestre { get; set; }
    }
}
