//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tarefa_entrega
    {
        public int cd_tarefa_entrega { get; set; }
        public long cd_pedido { get; set; }
        public short cd_status_entrega { get; set; }
        public string ds_motivo_tarefa_entrega { get; set; }
        public Nullable<System.DateTime> dt_tarefa_entrega { get; set; }
    
        public virtual tb_pedido tb_pedido { get; set; }
        public virtual tb_status_entrega tb_status_entrega { get; set; }
    }
}
