//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tipo_documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_tipo_documento()
        {
            this.tb_usuario_dependente_documento_banco = new HashSet<tb_usuario_dependente_documento_banco>();
            this.tb_usuario_documento_banco = new HashSet<tb_usuario_documento_banco>();
        }
    
        public short nu_tipo_documento { get; set; }
        public string ds_tipo_documento { get; set; }
        public string ds_documento_banco { get; set; }
        public bool ic_inativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuario_dependente_documento_banco> tb_usuario_dependente_documento_banco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuario_documento_banco> tb_usuario_documento_banco { get; set; }
    }
}
