//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tipo_pedido_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_tipo_pedido_item()
        {
            this.tb_tipo_pedido_item_fluxo_status = new HashSet<tb_tipo_pedido_item_fluxo_status>();
        }
    
        public int cd_tipo_pedido_item { get; set; }
        public string nm_tipo_pedido_item { get; set; }
        public Nullable<bool> ic_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_tipo_pedido_item_fluxo_status> tb_tipo_pedido_item_fluxo_status { get; set; }
    }
}
