//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_termo_operadora
    {
        public int cd_termo_operadora { get; set; }
        public string ds_versao_termo { get; set; }
        public Nullable<System.DateTime> dt_data_criacao { get; set; }
        public string ds_termo { get; set; }
        public Nullable<int> cd_operadora { get; set; }
        public Nullable<int> tp_tipo_pedido { get; set; }
        public Nullable<bool> ic_inativo { get; set; }
        public Nullable<System.DateTime> dt_data_inativo { get; set; }
    }
}
