//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_termo_de_uso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_termo_de_uso()
        {
            this.tb_usuario_termo_de_uso = new HashSet<tb_usuario_termo_de_uso>();
        }
    
        public short cd_termo_de_uso { get; set; }
        public short tp_termo_de_uso { get; set; }
        public string ds_termo_de_uso { get; set; }
        public System.DateTime dt_cadastro { get; set; }
        public int cd_usuario_adm { get; set; }
        public bool ic_inativo { get; set; }
        public bool ic_EMPRESA3mais { get; set; }
        public bool ic_revenda { get; set; }
    
        public virtual tb_usuario_adm tb_usuario_adm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuario_termo_de_uso> tb_usuario_termo_de_uso { get; set; }
    }
}
