//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tentativa_most
    {
        public long cd_tentativa_most { get; set; }
        public Nullable<long> cd_usuario { get; set; }
        public string nu_codigo_usuario_operadora { get; set; }
        public Nullable<System.DateTime> dt_tentativa { get; set; }
        public Nullable<bool> st_sucesso { get; set; }
        public Nullable<int> tp_responsavel { get; set; }
    }
}
