//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_transacao_conta_digital
    {
        public int cd_transacao_conta_digital { get; set; }
        public Nullable<int> cd_banco_conta_digital { get; set; }
        public Nullable<long> cd_usuario { get; set; }
        public Nullable<int> cd_tipo_transacao { get; set; }
        public Nullable<System.DateTime> dt_criacao_registro { get; set; }
        public Nullable<System.DateTime> dt_transacao_banco { get; set; }
        public string ds_token_transacao { get; set; }
        public Nullable<int> id_conta_origem { get; set; }
        public Nullable<int> id_conta_destino { get; set; }
        public Nullable<decimal> vl_valor { get; set; }
        public string ds_body_envio { get; set; }
        public Nullable<bool> ic_finalizada { get; set; }
        public string ds_chave_banco { get; set; }
        public string ds_retorno { get; set; }
        public string ds_ip_usuario { get; set; }
        public Nullable<bool> ic_expirado { get; set; }
        public Nullable<System.DateTime> dt_validade_token { get; set; }
    
        public virtual tb_banco_conta_digital tb_banco_conta_digital { get; set; }
        public virtual tb_tipo_transacao tb_tipo_transacao { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
