//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tipo_cartao_valor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_tipo_cartao_valor()
        {
            this.tb_pedido_item = new HashSet<tb_pedido_item>();
        }
    
        public int cd_tipo_cartao_valor { get; set; }
        public int cd_tipo_cartao { get; set; }
        public decimal vl_tipo_cartao { get; set; }
        public string ds_cod_externo { get; set; }
        public bool ic_inativo { get; set; }
        public string ds_item_tipo_cartao { get; set; }
        public string id_produto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_item> tb_pedido_item { get; set; }
        public virtual tb_tipo_cartao tb_tipo_cartao { get; set; }
    }
}
