//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tarifa
    {
        public int cd_tarifa { get; set; }
        public Nullable<int> cd_operadora { get; set; }
        public string ds_tarifa_cliente { get; set; }
        public string ds_tarifa { get; set; }
        public Nullable<decimal> vl_tarifa { get; set; }
        public Nullable<System.DateTime> dt_inicio_validade { get; set; }
        public Nullable<System.DateTime> dt_fim_validade { get; set; }
        public Nullable<System.DateTime> dt_cadastro { get; set; }
    }
}
