//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario_revenda_operadora
    {
        public int cd_usuario_revenda_operadora { get; set; }
        public long cd_usuario { get; set; }
        public int cd_operadora { get; set; }
        public Nullable<bool> ic_inativo { get; set; }
    
        public virtual tb_operadora tb_operadora { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
