//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario_conta_corrente
    {
        public long cd_usuario_conta_corrente { get; set; }
        public long cd_usuario { get; set; }
        public string tp_operacao { get; set; }
        public string ds_conta_corrente { get; set; }
        public System.DateTime dt_registro { get; set; }
        public decimal vl_registro { get; set; }
        public bool ic_inativo { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
