//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario_documento_banco
    {
        public long cd_usuario_documento_banco { get; set; }
        public long cd_usuario { get; set; }
        public short nu_tipo_documento { get; set; }
        public byte[] img_documento { get; set; }
        public System.DateTime dt_registro { get; set; }
        public string ds_tipo_documento { get; set; }
    
        public virtual tb_tipo_documento tb_tipo_documento { get; set; }
    }
}
