//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario_endereco
    {
        public long cd_usuario_endereco { get; set; }
        public long cd_usuario { get; set; }
        public string ds_tipo_logradouro { get; set; }
        public string nm_logradouro { get; set; }
        public int nu_logradouro { get; set; }
        public string ds_complemento_logradouro { get; set; }
        public string nm_bairro { get; set; }
        public string nm_municipio { get; set; }
        public short cd_uf { get; set; }
        public string nu_cep { get; set; }
        public string ds_codigo_ibge { get; set; }
        public bool ic_endereco_padrao { get; set; }
    
        public virtual tb_uf tb_uf { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
