//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario_banco_conta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_usuario_banco_conta()
        {
            this.tb_analise_spd_conta = new HashSet<tb_analise_spd_conta>();
            this.tb_pedido_cash_in = new HashSet<tb_pedido_cash_in>();
            this.tb_usuario_banco_conta_chave = new HashSet<tb_usuario_banco_conta_chave>();
        }
    
        public long cd_usuario_banco_conta { get; set; }
        public long cd_usuario { get; set; }
        public string ds_token_termo { get; set; }
        public string ds_token_privacidade { get; set; }
        public Nullable<long> id_usuario_banco { get; set; }
        public Nullable<long> id_conta { get; set; }
        public Nullable<short> cd_status_conta { get; set; }
        public System.DateTime dt_cadastro { get; set; }
        public Nullable<System.DateTime> dt_inativo { get; set; }
        public string ds_registration_id_conta { get; set; }
        public Nullable<long> id_cartao_virtual { get; set; }
        public string nu_senha_carteira { get; set; }
        public Nullable<System.DateTime> dt_conta_bloqueada { get; set; }
        public string ds_status_abertura { get; set; }
        public Nullable<System.DateTime> dt_cadastro_finalizado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_analise_spd_conta> tb_analise_spd_conta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_cash_in> tb_pedido_cash_in { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuario_banco_conta_chave> tb_usuario_banco_conta_chave { get; set; }
    }
}
