//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario_cartao_favorito_linha
    {
        public long cd_usuario_cartao_favorito_linha { get; set; }
        public long cd_usuario_cartao { get; set; }
        public string ds_linha { get; set; }
        public string ds_id_linha_sbe { get; set; }
    
        public virtual tb_usuario_cartao tb_usuario_cartao { get; set; }
    }
}
