//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario_cartao_credito_endereco_cobranca
    {
        public long cd_usuario_cartao_credito_endereco_cobranca { get; set; }
        public long cd_usuario_cartao_credito { get; set; }
        public string ds_tipo_logradouro_cobranca { get; set; }
        public string nm_logradouro_cobranca { get; set; }
        public int nu_logradouro_cobranca { get; set; }
        public string ds_complemento_logradouro_cobranca { get; set; }
        public string nm_bairro_cobranca { get; set; }
        public string nm_municipio_cobranca { get; set; }
        public string nm_uf { get; set; }
        public string nu_cep_cobranca { get; set; }
        public string ds_codigo_ibge_cobranca { get; set; }
        public bool ic_endereco_padrao_cobranca { get; set; }
        public bool ic_endereco_cobranca_inativo { get; set; }
    
        public virtual tb_usuario_cartao_credito tb_usuario_cartao_credito { get; set; }
    }
}
