//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario_adm_operadora_empresa
    {
        public int cd_usuario_adm_operadora_empresa { get; set; }
        public int cd_operadora_empresa { get; set; }
        public int cd_usuario_adm { get; set; }
        public bool ic_inativo { get; set; }
    
        public virtual tb_operadora_empresa tb_operadora_empresa { get; set; }
        public virtual tb_usuario_adm tb_usuario_adm { get; set; }
    }
}
