//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario_favorito_linha
    {
        public long cd_usuario_favorito_linha { get; set; }
        public Nullable<long> cd_usuario { get; set; }
        public Nullable<int> cd_operadora { get; set; }
        public string ds_linha { get; set; }
        public string ds_id_linha_sbe { get; set; }
        public Nullable<int> cd_linha_mapa { get; set; }
        public string ds_linha_mapa { get; set; }
        public string nm_linha_mapa { get; set; }
    
        public virtual tb_operadora tb_operadora { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
