//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario_revenda_pre_estocagem
    {
        public int cd_usuario_revenda_pre_estocagem { get; set; }
        public long cd_usuario { get; set; }
        public System.DateTime dt_pre_estocagem { get; set; }
        public decimal vl_pre_estocagem { get; set; }
        public System.DateTime dt_log { get; set; }
        public int cd_usuario_adm { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
        public virtual tb_usuario_adm tb_usuario_adm { get; set; }
    }
}
