//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario_equipamento
    {
        public int cd_usuario_equipamento { get; set; }
        public Nullable<long> cd_usuario { get; set; }
        public string ds_equipamento { get; set; }
        public string ds_imei { get; set; }
        public System.DateTime dt_cadastro { get; set; }
        public bool ic_inativo { get; set; }
        public Nullable<System.DateTime> dt_inativo { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
