//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario_cartao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_usuario_cartao()
        {
            this.tb_bloqueio_cartao = new HashSet<tb_bloqueio_cartao>();
            this.tb_EMPRESA3lometros = new HashSet<tb_EMPRESA3lometros>();
            this.tb_log_usuario_cartao = new HashSet<tb_log_usuario_cartao>();
            this.tb_recarga_automatica = new HashSet<tb_recarga_automatica>();
            this.tb_recarga_programada = new HashSet<tb_recarga_programada>();
            this.tb_tipo_cartao_estoque = new HashSet<tb_tipo_cartao_estoque>();
            this.tb_usuario_cartao_favorito_linha = new HashSet<tb_usuario_cartao_favorito_linha>();
        }
    
        public long cd_usuario_cartao { get; set; }
        public long cd_usuario { get; set; }
        public int cd_tipo_cartao { get; set; }
        public string nm_cartao { get; set; }
        public string nu_cartao { get; set; }
        public string nu_fisico { get; set; }
        public System.DateTime dt_cadastro_cartao { get; set; }
        public decimal vr_saldo { get; set; }
        public string dt_saldo_atualizado { get; set; }
        public bool ic_cartao_inativo { get; set; }
        public bool ic_cartao_bloqueado { get; set; }
        public bool ic_cartao_favorito { get; set; }
        public bool ic_cartao_favorito_EMPRESA3lometros { get; set; }
        public bool ic_revenda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_bloqueio_cartao> tb_bloqueio_cartao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_EMPRESA3lometros> tb_EMPRESA3lometros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_log_usuario_cartao> tb_log_usuario_cartao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_recarga_automatica> tb_recarga_automatica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_recarga_programada> tb_recarga_programada { get; set; }
        public virtual tb_tipo_cartao tb_tipo_cartao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_tipo_cartao_estoque> tb_tipo_cartao_estoque { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuario_cartao_favorito_linha> tb_usuario_cartao_favorito_linha { get; set; }
    }
}
