//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario_adm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_usuario_adm()
        {
            this.tb_black_list = new HashSet<tb_black_list>();
            this.tb_crm_relacionamento = new HashSet<tb_crm_relacionamento>();
            this.tb_crm_relacionamento_usr_atribuido = new HashSet<tb_crm_relacionamento_usr_atribuido>();
            this.tb_crm_relacionamento_usr_atribuido1 = new HashSet<tb_crm_relacionamento_usr_atribuido>();
            this.tb_estorno_pedido = new HashSet<tb_estorno_pedido>();
            this.tb_estorno_pedido1 = new HashSet<tb_estorno_pedido>();
            this.tb_fila_analise_revalidacao = new HashSet<tb_fila_analise_revalidacao>();
            this.tb_log_black_list = new HashSet<tb_log_black_list>();
            this.tb_log_black_list_usuario_forma_pagamento = new HashSet<tb_log_black_list_usuario_forma_pagamento>();
            this.tb_log_pedido_item_cancelamento_rv = new HashSet<tb_log_pedido_item_cancelamento_rv>();
            this.tb_log_usuario_alteracao = new HashSet<tb_log_usuario_alteracao>();
            this.tb_log_usuario_revenda_comissao = new HashSet<tb_log_usuario_revenda_comissao>();
            this.tb_log_usuario_revenda_limite = new HashSet<tb_log_usuario_revenda_limite>();
            this.tb_pedido_item_cartao = new HashSet<tb_pedido_item_cartao>();
            this.tb_pedido_item_cartao1 = new HashSet<tb_pedido_item_cartao>();
            this.tb_termo_de_uso = new HashSet<tb_termo_de_uso>();
            this.tb_usuario_adm_operadora_empresa = new HashSet<tb_usuario_adm_operadora_empresa>();
            this.tb_usuario_revenda_pre_estocagem = new HashSet<tb_usuario_revenda_pre_estocagem>();
        }
    
        public int cd_usuario_adm { get; set; }
        public string nm_login_adm { get; set; }
        public string nm_usuario_adm { get; set; }
        public string ds_senha_usuario_adm { get; set; }
        public bool ic_usario_adm_inativo { get; set; }
        public Nullable<short> cd_perfil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_black_list> tb_black_list { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_crm_relacionamento> tb_crm_relacionamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_crm_relacionamento_usr_atribuido> tb_crm_relacionamento_usr_atribuido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_crm_relacionamento_usr_atribuido> tb_crm_relacionamento_usr_atribuido1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_estorno_pedido> tb_estorno_pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_estorno_pedido> tb_estorno_pedido1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_fila_analise_revalidacao> tb_fila_analise_revalidacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_log_black_list> tb_log_black_list { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_log_black_list_usuario_forma_pagamento> tb_log_black_list_usuario_forma_pagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_log_pedido_item_cancelamento_rv> tb_log_pedido_item_cancelamento_rv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_log_usuario_alteracao> tb_log_usuario_alteracao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_log_usuario_revenda_comissao> tb_log_usuario_revenda_comissao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_log_usuario_revenda_limite> tb_log_usuario_revenda_limite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_item_cartao> tb_pedido_item_cartao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido_item_cartao> tb_pedido_item_cartao1 { get; set; }
        public virtual tb_perfil tb_perfil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_termo_de_uso> tb_termo_de_uso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuario_adm_operadora_empresa> tb_usuario_adm_operadora_empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuario_revenda_pre_estocagem> tb_usuario_revenda_pre_estocagem { get; set; }
    }
}
