//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario_cartao_credito_gateway_token
    {
        public long cd_usuario_cartao_credito_gateway_token { get; set; }
        public long cd_usuario_cartao_credito { get; set; }
        public short cd_gateway { get; set; }
        public string ds_token { get; set; }
        public System.DateTime dt_cadastro { get; set; }
        public bool ic_inativo { get; set; }
    
        public virtual tb_gateway tb_gateway { get; set; }
        public virtual tb_usuario_cartao_credito tb_usuario_cartao_credito { get; set; }
    }
}
