//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_valores_sptrans
    {
        public int cd_tarifa { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string descricao_tarifa { get; set; }
        public Nullable<int> tipo_tarifa { get; set; }
        public Nullable<int> qtd_maxima { get; set; }
        public Nullable<int> qtd_minima { get; set; }
    }
}
