//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bi_tb_operadora
    {
        public int cd_operadora { get; set; }
        public string nu_cnpj_operadora { get; set; }
        public string nm_fantasia_operadora { get; set; }
        public string nm_sigla_operadora { get; set; }
        public bool ic_operadora_inativo { get; set; }
        public bool ic_recarga_cartao_transporte { get; set; }
        public bool ic_recarga_celular { get; set; }
        public bool ic_recarga_servicos_digitais { get; set; }
        public bool ic_recarga_tv_prepaga { get; set; }
        public bool ic_revenda { get; set; }
        public bool ic_revenda_especial { get; set; }
    }
}
