//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bi_usuario_cadastro_cartao
    {
        public long cd_usuario { get; set; }
        public long cd_usuario_cartao { get; set; }
        public int cd_tipo_cartao { get; set; }
        public string dt_cadastro_cartao { get; set; }
        public string dt_quinzena { get; set; }
        public string dt_mes { get; set; }
        public Nullable<int> dt_ano { get; set; }
        public int cd_operadora { get; set; }
    }
}
