//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bi_tb_tipo_cartao
    {
        public int cd_tipo_cartao { get; set; }
        public int cd_operadora { get; set; }
        public string ds_tipo_cartao { get; set; }
        public decimal vl_minimo_credito { get; set; }
        public decimal vl_maximo_credito { get; set; }
    }
}
