//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bi_relacionamento_usuario
    {
        public decimal cd_relacionamento { get; set; }
        public short cd_perfil { get; set; }
        public Nullable<System.DateTime> dt_inicio_relacionamento { get; set; }
        public short cd_motivo_relacionamento { get; set; }
        public int cd_usuario_adm { get; set; }
        public short cd_tipo_relacionamento { get; set; }
        public string ds_situacao_relacionamento { get; set; }
        public long cd_usuario { get; set; }
        public string nm_usuario { get; set; }
        public string ds_email_usuario { get; set; }
        public string nu_cnpj_usuario { get; set; }
        public string nu_cpf_usuario { get; set; }
        public string cd_protocolo { get; set; }
        public Nullable<System.DateTime> dt_fim_relacionamento { get; set; }
    }
}
