//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bi_vendas
    {
        public string dt_datahora_pedido { get; set; }
        public short cd_status_pedido { get; set; }
        public Nullable<short> cd_status_pedido_item { get; set; }
        public short cd_forma_pagamento { get; set; }
        public long cd_usuario { get; set; }
        public Nullable<int> cd_operadora { get; set; }
        public Nullable<int> cd_tipo_cartao { get; set; }
        public Nullable<long> cd_pedido_item { get; set; }
        public Nullable<int> cd_taxa_operadora_tipo_cartao { get; set; }
        public Nullable<short> cd_canal { get; set; }
        public Nullable<short> tp_pedido_item { get; set; }
        public string nu_cartao { get; set; }
        public string nu_ddd { get; set; }
        public string nu_tel { get; set; }
        public string ServicoDigital { get; set; }
        public Nullable<decimal> vl_pedido { get; set; }
        public Nullable<decimal> vl_taxa { get; set; }
        public Nullable<decimal> vl_desconto { get; set; }
        public Nullable<decimal> vl_total_entrega { get; set; }
        public Nullable<decimal> vl_total_pedido { get; set; }
        public Nullable<decimal> vl_valor_pago { get; set; }
        public string ds_pedido_operadora { get; set; }
        public string dt_datahora_estocagem { get; set; }
        public long cd_pedido { get; set; }
        public string ds_codigo { get; set; }
        public Nullable<decimal> vl_percentual_faturamento { get; set; }
        public Nullable<decimal> tx_servico { get; set; }
        public Nullable<decimal> receita_operadora { get; set; }
        public string nm_sigla_operadora { get; set; }
        public Nullable<short> cd_gateway { get; set; }
    }
}
