//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bi_tb_usuario_pedido
    {
        public long cd_pedido { get; set; }
        public long cd_pedido_item { get; set; }
        public long cd_usuario { get; set; }
        public System.DateTime dt_datahora_pedido { get; set; }
        public Nullable<System.DateTime> dt_datahora_pedido_operadora { get; set; }
        public decimal ValorItem { get; set; }
        public decimal vl_total_pedido { get; set; }
        public short tp_pedido_item { get; set; }
        public short cd_forma_pagamento { get; set; }
        public Nullable<long> cd_usuario_cartao { get; set; }
        public Nullable<int> cd_tipo_cartao { get; set; }
        public int cd_operadora { get; set; }
    }
}
