//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bi_tb_usuario_adm
    {
        public int cd_usuario_adm { get; set; }
        public string nm_login_adm { get; set; }
        public string nm_usuario_adm { get; set; }
        public bool ic_usario_adm_inativo { get; set; }
        public Nullable<short> cd_perfil { get; set; }
    }
}
