//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Cupom_Disponivel_Usuario
    {
        public long cd_usuario { get; set; }
        public long cd_usuario_cupom { get; set; }
        public long cd_cupom { get; set; }
        public string ds_codigo { get; set; }
        public string ds_cupom_conteudo { get; set; }
        public System.DateTime dt_cadastro { get; set; }
        public System.DateTime dt_validade { get; set; }
        public Nullable<decimal> vl_desconto { get; set; }
        public string tp_cupom { get; set; }
    }
}
