//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EMPRESA3lometros_agrupados
    {
        public Nullable<int> pontos { get; set; }
        public long cd_usuario { get; set; }
        public Nullable<long> cd_usuario_banco_conta { get; set; }
        public Nullable<long> id_conta { get; set; }
        public Nullable<short> cd_status_conta { get; set; }
    }
}
