//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Pedidos_AntiFraude
    {
        public long cd_usuario { get; set; }
        public short tp_pedido_item { get; set; }
        public Nullable<System.DateTime> data_pedido { get; set; }
        public Nullable<int> qtd_pedidos { get; set; }
    }
}
