//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_pedidos_pagar_operadora
    {
        public long cd_usuario { get; set; }
        public int cd_operadora { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string ds_chave_processamento { get; set; }
    }
}
