//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ServicosOperadoras
    {
        public int CodOperadora { get; set; }
        public string NomeOperadora { get; set; }
        public string LogoOperadora { get; set; }
        public int possuiMapa { get; set; }
        public int possuiQRCode { get; set; }
        public int possuiBloqueio { get; set; }
        public int possuiPrimeiraVia { get; set; }
        public int possuiSegundaVia { get; set; }
        public int possuiRevalidacao { get; set; }
        public int possuiIntegracao { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public Nullable<int> raio { get; set; }
        public Nullable<decimal> ValorTarifa { get; set; }
        public Nullable<decimal> ValorMaxQrCode { get; set; }
        public Nullable<decimal> ValorMinQrCode { get; set; }
        public int CodigoCidade { get; set; }
        public string NomeCidade { get; set; }
        public int HasExtrato { get; set; }
    }
}
