//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicoConfirmaRecargaSpTrans.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UsuarioCartaoOperadora
    {
        public long cd_usuario { get; set; }
        public string nm_municipio { get; set; }
        public long cd_usuario_cartao { get; set; }
        public string nu_cartao { get; set; }
        public System.DateTime dt_cadastro_cartao { get; set; }
        public int cd_operadora { get; set; }
        public string nm_fantasia_operadora { get; set; }
        public string nm_cidade { get; set; }
        public decimal nu_latitude { get; set; }
        public decimal nu_longitude { get; set; }
        public Nullable<int> nu_raio { get; set; }
        public string dt_saldo_atualizado { get; set; }
    }
}
